### ISSUE TITLE
Missing ICU Symbol

### ISSUE THREAD

**Issue by lluuaapp** [grosjo/fts-xapian#10]
Seems there is a lib missing in the configure/Make file script:

```
Jan 23 13:41:38 mail dovecot: imap(license@iwascoding.com): Error: Couldn't load required plugin /usr/local/dovecot/lib/dovecot/lib21_fts_xapian_plugin.so: dlopen() failed: /usr/local/dovecot/lib/dovecot/lib21_fts_xapian_plugin.so: undefined symbol: _ZTIN6icu_578ByteSinkE
```

I am not exactly sure what libraries are missing, but changing `LIBS = ` to `LIBS = -licuio -licui18n -licuuc -licudata` in src/Makefile fixes it for me.

**Comment by grosjo** [comment]
See https://github.com/grosjo/fts-xapian/commit/ee320bb304c2533bafd3c00b9d657432ed4b231e

Does it compile properly for you this way ?

**Comment by lluuaapp** [comment]
No, sorry. I think you have to calculate the libs with
```
pkg-config --libs --cflags icu-uc
```
This returns `-licuuc -licudata`. So maybe you need to link to both libs?

**Comment by grosjo** [comment]
added. Better for you ?
(why do I do not need it on my archlinux server ?)

**Comment by grosjo** [comment]
Somehow, I am not able to make sure the libicu is linked at compile time in Makefile.am and configure.ac.
Can you help ?
Thank you so much

**Comment by lluuaapp** [comment]
Somehow I figured out how to add the libs with autoconf.

Don't not know why you do not need these libs. Maybe because dovecot is already linked against them?

Will create a PR in a minute.
