### ISSUE TITLE
Error when installing oplugin

### ISSUE THREAD

**Issue by Seoxsc** [grosjo/fts-xapian#111]
After installing the plugin DOVECOT crashes with:
Error: Couldn't load required plugin /usr/lib/dovecot/modules/lib21_fts_xapian_plugin.so: Module is for different ABI version 2.3.ABIv4(2.3.4.1) (we have 2.3.ABIv17(2.3.17))
Is there a way to bypass this

**Comment by grosjo** [comment]
How are you installing it ? (source / package) 
Which OS ?

**Comment by Seoxsc** [comment]
Greetings, Debian Buster, installed from source (following the instructions
from https://github.com/grosjo/fts-xapian )

**Comment by grosjo** [comment]
if you install from source, there can not be any ABI discrepancies

Are you really using the source from github ?

**Comment by Seoxsc** [comment]
Yes:  git clone https://github.com/grosjo/fts-xapian

**Comment by grosjo** [comment]
@Seoxsc Maybe the "make install" does not install in the binary in the right place. Have you checked the modules used by dovecot are the one you compiled ?

**Comment by grosjo** [comment]
@Seoxsc any news on that ?

**Comment by Seoxsc** [comment]
Greetings, yes I double checked, just to make sure I deleted
the fts_xapian files from  /usr/lib/dovecot/modules  and recompiled
everything, Dovecot is using:

ls -al /usr/lib/dovecot/modules/lib21_fts*
-rw-r--r-- 1 root root 2847844 Dec 31 08:05 lib21_fts_xapian_plugin.a
-rwxr-xr-x 1 root root    1119 Dec 31 08:05 lib21_fts_xapian_plugin.la
-rwxr-xr-x 1 root root 1171496 Dec 31 08:05 lib21_fts_xapian_plugin.so

Same error:
Couldn't load required plugin
/usr/lib/dovecot/modules/lib21_fts_xapian_plugin.so: Module is for
different ABI version 2.3.ABIv4(2.3.4.1) (we have 2.3.ABIv17(2.3.17))

**Comment by slavkoja** [comment]
It seems that you build it against buster's dovecot sources, which is  version 2.3.4.1, but you are using the 2.3.17.

You have to build plugin against source version, which you are using (or more precise with the same ABI version), as ABI is not compatible, as cleanly stated in error message.

**Comment by grosjo** [comment]
@Seoxsc is that resolved ?

**Comment by grosjo** [comment]
@Seoxsc I believe this is solved. Feel free to reopen if not

**Comment by Seoxsc** [comment]
Greetings, I tried everything but it didn't work.

**Comment by grosjo** [comment]
@Seoxsc Maybe try (1) compiling/installing dovecot from sources (2) compiling/installing pigeonhole from sources (3) compiling/installing fts-xapian
