### ISSUE TITLE
Matrix room does not seem to exist

### ISSUE THREAD

**Issue by madduck** [grosjo/fts-xapian#114]
I tried to join `#xapian-dovecot:grosjo.net`, which the documentation says exists, but `grosjo.net` does not have a Matrix server associated with it.

**Comment by grosjo** [comment]
yes, I have a setup issue on this, will try to re-setup my matrix server

**Comment by grosjo** [comment]
@madduck I have the followinf error, and no clue why (updated to latest version ) (ArchLInux)

Mar 12 12:45:33 gjserver systemd[1]: Starting Synapse Matrix homeserver (master)...
Mar 12 12:45:33 gjserver systemd[53633]: synapse.service: Failed to set up special execution directory in /var/lib: Not a directory
Mar 12 12:45:33 gjserver systemd[53633]: synapse.service: Failed at step STATE_DIRECTORY spawning /usr/bin/python3: Not a directory
Mar 12 12:45:33 gjserver systemd[1]: synapse.service: Main process exited, code=exited, status=238/STATE_DIRECTORY
Mar 12 12:45:33 gjserver systemd[1]: synapse.service: Failed with result 'exit-code'.

**Comment by grosjo** [comment]
@madduck can you try with #xapian-dovecot:matrix.grosjo.net ?

**Comment by madduck** [comment]
> @madduck can you try with #xapian-dovecot:matrix.grosjo.net ?

That works.

**Comment by grosjo** [comment]
Cool
