### ISSUE TITLE
Folder xapian-indexes shows up as IMAP folder for clients

### ISSUE THREAD

**Issue by madduck** [grosjo/fts-xapian#115]
The plugin puts the indices into a folder `xapian-indexes` in the mail root folder. While not a valid Maildir, this still causes clients, such as Apple Mail and Thunderbird to show a new folder, when Dovecot is configured with `layout=fs`.

Could the location of the indices be made configurable? Ideally, I'd like for the indices to sit outside of the mail root, even.

**Comment by DerLinkman** [comment]
Would like to request this feature as well!

We´re currently replacing solr with XAPIAN (for the mailcow-dockerized project) and it would be awesome to set the path of the indexes.

**Comment by grosjo** [comment]
@madduck @DerLinkman  Location of indexes is a dovecot feature
https://doc.dovecot.org/configuration_manual/mail_location/
this plugin follow the said confiruation in dovecot.conf

**Comment by grosjo** [comment]
example : mail_location = mdbox:/MYLOCATION/%d/%n:INDEX=/OTHERLCOATION/%d/%n

**Comment by DerLinkman** [comment]
Thank you @grosjo ! I didn´t knew that.

**Comment by grosjo** [comment]
@DerLinkman  @madduck I beleive this is solved. Reopen if you feel so
