### ISSUE TITLE
no email found when request contains dash

### ISSUE THREAD

**Issue by symphorien** [grosjo/fts-xapian#126]
I have an email containing `nixos-upgrade.service`. If I do a full text search for `upgrade.service` it is found but not for `nixos-upgrade.service`.

**Comment by sheckandar** [comment]
I just noticed the same thing. If I need to find a string 12345-6 and I search for 12345, the results are correct, but if I search for 12345-6, there are no results returned.

RedHat 8.7
Dovecot 2.3.20
Latest Xapian compiled from code in this repo

**Comment by OlafTitz** [comment]
Took me a long time of debugging to realize that this breaks Asterisk IMAP Voicemail.
Asterisk does queries like "HEADER X-Asterisk-VM-Context: default" and gets no results.
Ubuntu 22.04, Dovecot 2.3.16, fts-xapian 1.5.2

**Comment by grosjo** [comment]
You probably need to go to 1.5.5

**Comment by grosjo** [comment]
Release 1.5.6
