### ISSUE TITLE
Any plans for EPEL 9?

### ISSUE THREAD

**Issue by ghtm2** [grosjo/fts-xapian#127]
Hi,

if it's not too much of a hassle, would you be able to push the package to EPEL 9 as well?

I've successfully used the spec file on AlmaLinux 9, so that should at least not be a problem.

Thanks.

**Comment by mjuric** [comment]
Hi @grosjo -- I notice this issue was closed as completed, but I couldn't find an [EPEL 9 build](https://koji.fedoraproject.org/koji/packageinfo?packageID=34417).

Just checking if I'm possibly looking in the wrong place (I'm hoping to install it on Rocky Linux 9).

**Comment by grosjo** [comment]
You better install it from source
