### ISSUE TITLE
configure --prefix ignored

### ISSUE THREAD

**Issue by leezu** [grosjo/fts-xapian#14]
Hi @grosjo, thank you for developing this package. I noted that `PANDOC=false ./configure --prefix=/usr/local --with-dovecot=/usr/lib/dovecot`, compiling and finally installing via `make install` will put the module to `/usr/lib/dovecot` instead of `/usr/local/lib/dovecot` as I would have expected from specifying a `--prefix`.

I am not sure, if loading modules from `/usr/local/` is feasible, as eg. the `fts` plugin would remain in `/usr/lib/dovecot/modules` and as dovecot configuration variable `mail_plugin_dir` seems to expect a single directory.

Could you clarify the purpose of specifying the prefix? If only `--with-dovecot` is taken into account, should the `--prefix` be removed from the example in the readme together with a clarification that the module must be installed in the `--with-dovecot` directory? On the other hand, if it is actually meaningful to install the module to `/usr/local/`, please consider fixing the installation script.

**Comment by grosjo** [comment]
You are right, the --prefix is useless
