### ISSUE TITLE
Search string limitation between 3 and 20 characters

### ISSUE THREAD

**Issue by clesssalvein** [grosjo/fts-xapian#140]
Hello!

Why is there a limitation to search for a string with a length of at least 3 characters? Sometimes, for example, it's necessary to find even only one character in the text. Is there an option to make the plugin allow to search a string less than 3 characters?

**Comment by grosjo** [comment]
![image](https://github.com/grosjo/fts-xapian/assets/2287111/dc25e722-0028-47e0-8b2e-dc3808c63877)
Yes, you put partial=2 ;)

**Comment by clesssalvein** [comment]
Oh, sorry. I've forgotten to reindex the mailboxes after the changing the configuration.
Now it works. Thank you!
