### ISSUE TITLE
Can't find emails by full attachment filename

### ISSUE THREAD

**Issue by sirAlexanderSokolov** [grosjo/fts-xapian#141]
Greetings! I'm using fts-xapian on debian 12 with default settings:

```
    fts = xapian
    fts_xapian = partial=3 full=20

    fts_autoindex = yes
    fts_enforced = yes

    fts_autoindex_exclude = \Trash

    # Index attachements
    fts_decoder = decode2text
```
Seems like the full-text search is not functioning optimally with attachment filenames. I am unable to locate emails when searching by the complete word, but successful when searching with partial words:

![Screenshot_2023-11-07_19-34-44](https://github.com/grosjo/fts-xapian/assets/52035309/438eb23b-76ec-40c8-998c-775dee8c0695)

![Screenshot_2023-11-07_19-35-23](https://github.com/grosjo/fts-xapian/assets/52035309/4162b506-1930-4446-bc93-66559a7682a9)

![Screenshot_2023-11-07_19-36-21](https://github.com/grosjo/fts-xapian/assets/52035309/c4e0850d-b76c-4048-87bf-920e10ce0514)

Can you advice me please how can i fix it?

**Comment by grosjo** [comment]
In roudcube, choose "Body" as the location of search

**Comment by grosjo** [comment]
Solved ?

**Comment by grosjo** [comment]
If problem remains with latest git, feel free to reopen
