### ISSUE TITLE
is 'attachments=0' a real option?

### ISSUE THREAD

**Issue by petersphilo** [grosjo/fts-xapian#142]
Hello,
i've been trying to 'tune' fts-xapian on my server, and i often see this option in posts, but not in the docs:
`attachments=0`

as in an example:
`fts_xapian = partial=3 full=8 attachments=0 verbose=0`

is this a real option?
Doesn't fts-xapian ignore attachments by default?
Thank You Very Much!!

**Comment by grosjo** [comment]
Hi @petersphilo 

No, the parameter existed before, but the easy way is just to remove the "fts_decoder = decode2text"  in dovecot.conf

**Comment by petersphilo** [comment]
Thank You so much for the response!
that's what i thought..
so, basically, not setting 'fts_decoder' in the conf file ensures that attachments will be skipped, right?
Thank You again for all your work!
