### ISSUE TITLE
not building on macOS, NetBSD, perhaps others

### ISSUE THREAD

**Issue by schmonz** [grosjo/fts-xapian#151]
Some portability problems have cropped up:

- NetBSD does not have `<vm/vm_param.h>` (nearest equivalent _might_ be `<uvm/uvm_param.h>`, not sure whether/how it relates)
- On macOS, there's no `cuserid()` available; it's [not gone yet from NetBSD](https://man.netbsd.org/cuserid.3#BUGS)
- In the FreeBSD/NetBSD/macOS branch of `fts-backend-xapian-functions.cpp:fts_backend_xapian_get_free_memory()`, `limit` hasn't been declared yet

I'd be glad to prepare a PR adding a GitHub workflow that builds for a handful of platforms on push, if that's something you'd be interested in.

**Comment by grosjo** [comment]
Hi
Thank you for that
Can you test latest git ?

**Comment by schmonz** [comment]
All better except for [error: 'limit' was not declared in this scope; did you mean 'rlimit'?](https://github.com/grosjo/fts-xapian/blob/552c2be187f2ea89469ea0ffd4ffe9b7d42bce41/src/fts-backend-xapian-functions.cpp#L541)

**Comment by grosjo** [comment]
Try again latest git ?

**Comment by schmonz** [comment]
Yes, as of 
9589099 it builds to completion on both macOS and NetBSD. Thank you!

**Comment by grosjo** [comment]
Great to hear
