### ISSUE TITLE
Is it still required to add a daily cron job to run `doveadm fts optimize -A`?

### ISSUE THREAD

**Issue by iredmail** [grosjo/fts-xapian#160]
Dear @grosjo,

[Dovecot document](https://doc.dovecot.org/3.0/man/doveadm-fts.1/#fts-optimize) says `it's done automatically by the FTS engine`:

> `doveadm fts optimize [-u user | -A | -F file] [-S socket_path] [namespace]`
>
> Optimize the full text search index. This is also __done automatically by the full text search engines__, but this enforces it to happen.

But your document says `You shall put in a cron the following command (for daily run for instance)`.
So the question is, is it still required to add such daily cron job to run `doveadm fts optimize -A`?

**Comment by grosjo** [comment]
It is not required, but the there is no certainty that this cleanup is triggered regularly by dovecot, so better put it in your cron. If you don't, some index may get bigger for no reason, not an issue I beleive just a concern.
