### ISSUE TITLE
Does not index content-type

### ISSUE THREAD

**Issue by exi** [grosjo/fts-xapian#161]
I configured my dovecot with `fts_header_includes = *` to force indexing of all headers.

However my logs for xapian indexing are full of:

```
Info: FTS Xapian: New part (Header=Content-Type,Type=(null),Disposition=(null))
Info: FTS Xapian: Unknown header 'contenttype' of part
Info: FTS Xapian: fts_backend_xapian_update_set_build_key
Info: FTS Xapian: New part (Header=MIME-Version,Type=(null),Disposition=(null))
Info: FTS Xapian: Unknown header 'mimeversion' of part
Info: FTS Xapian: fts_backend_xapian_update_set_build_key
```

This suggests (also while reading the code) that it is not indexing anything beyond a few headers hard-coded in the fts-xapian code.

However many mail clients (Roundcube for example) need for example the `Content-Type` header indexed in order to support the "Show only mails with attachments" features.

**Comment by grosjo** [comment]
Please check latest git

**Comment by exi** [comment]
Awesome, thank you for the change!
