### ISSUE TITLE
gcc compilation error

### ISSUE THREAD

**Issue by lovedownload** [grosjo/fts-xapian#165]
hello.

I'm currently trying to update to the latest version.
When downloading the latest version and running make, the following error occurs.

--> g++: error: unrecognized command line option '-std=gnu++20'

The gcc version currently used by the Linux server is 4.8.5.
I am wondering if there will be any problem if I change the '-std=gnu++20' part of the Makefile under src to '-std=gnu++11' and compile.
Or do I need to update the gcc version and compile it?

The current system specs are as follows.

os : centos 7.9
gcc : 4.8.5
current fts-xapain : 1.5.5
upgrade fts-xapain : 1.7.14

**Comment by grosjo** [comment]
Hi
Gcc is now version 14.1, so 4.8.x seems very very old
But if your ICU libray is also super old, putting -std=gnu++11 shall work

**Comment by grosjo** [comment]
Let me know if that solves your issue

**Comment by lovedownload** [comment]
Compilation went smoothly, but we need to check if there are any problems with use.

**Comment by grosjo** [comment]
the gnu++20 is just for recent ICU, otehrwise, it has no impact
