### ISSUE TITLE
Strange uid/gid on xapian indexes

### ISSUE THREAD

**Issue by Forza-tng** [grosjo/fts-xapian#168]
Hi,

I have a mail server with only virtual users. Exim receives new mail, delivers the mail via LMTP to Dovecot. User names are looked up against a SQL server so i have dovecot set to use a fixed uid/gid for the maildirs since there are no local users.

My issue that the `iamglass` file sometimes is created as uid=0 instead of the dovecot user.

### dovecot.log
```
Jul 24 17:21:03 e350 dovecot: indexer-worker(system@redacted.domain)<53913><rPvxmvod6sXAqAAB:WDvVKN0boWaZ0gAAvmDbbg>: Error: FTS Xapian: Can't open Xapian DB /var/spool/mail/indexes/redacted.domain/system/xapian-indexes/db_5824672106493966b6220000be60db6e 2 : DatabaseOpeningError - /var/spool/mail/indexes/redacted.domain/system/xapian-indexes/db_5824672106493966b6220000be60db6e/iamglass: Failed to open glass revision file for reading
Permission denied
```

### directory listing
```

❯ ll /var/spool/mail/indexes/redacted.domain/system/xapian-indexes/db_5824672106493966b6220000be60db6e/
total 897732
drwsrwsr-x 1 vmail vmail       198 Jul 16 11:16 ./
drwsrwsr-x 1 vmail vmail      7392 Jul 24 17:21 ../
-rw-rw---- 1 vmail vmail      8192 Jun 21 20:13 docdata.glass
-rw-rw---- 1 vmail vmail         0 Jul 24 17:21 flintlock
-rw------- 1 root  vmail       146 Jul 16 11:16 iamglass
-rw-rw---- 1 vmail vmail      8192 Jun 21 20:13 position.glass
-rw-rw---- 1 vmail vmail 801308672 Jul 16 11:16 postlist.glass
-rw-rw---- 1 vmail vmail      8192 Jun 21 20:13 spelling.glass
-rw-rw---- 1 vmail vmail      8192 Jun 21 20:13 synonym.glass
-rw-rw---- 1 vmail vmail 117923840 Jul 16 11:16 termlist.glass
```

According to https://doc.dovecot.org/configuration_manual/service_configuration/ the `index-worker` service starts as root but then drops to the mail user's uid. Could this be related to the iamglass file being created as root while all other files are created using the correct user?

**Comment by listumps** [comment]
Exactly the same issue here. Sporadically happening every other day.

Currently running configuration:

Ubuntu 24.04.1 LTS
dovecot-core 2.3.21
dovecot-fts-xapian 1.6.0

Please provide correct way for debugging so we can give more useful info with the case.

**Comment by listumps** [comment]
Upgraded to dovecot-fts-xapian 1.7.14 without changing anything else and everything works fine for a week now. Seems like a bug in v.1.6.0

**Comment by grosjo** [comment]
Keep me updated with 1.7.16

**Comment by grosjo** [comment]
Kindly re-open if the problem continues
