### ISSUE TITLE
Fedora packaging, license question

### ISSUE THREAD

**Issue by neverpanic** [grosjo/fts-xapian#174]
I'm working on reviving the Fedora package at https://bugzilla.redhat.com/show_bug.cgi?id=2315641.
To get that going, I'm planning to apply the following patch to the spec file: https://src.fedoraproject.org/fork/clang/rpms/dovecot-fts-xapian/c/04d7ad9c8a42ece0f0a8def74fa64b2810b2005e

My reviewer noticed that you have a copy of a spec file for Fedora in this repository. Is that something we should try to keep updated, or should we let it rot, or remove it?

Also, could you please clarify whether the license of this project is LGPL-2.1-only or LGPL-2.1-or-later? That really doesn't become clear from the license files in the repository (or I couldn't find a place where it is clarified).

**Comment by grosjo** [comment]
Thank you for taking care of that

You can scrap out my previous attempts to package the plugin for Fedora, no problems

**Comment by neverpanic** [comment]
OK. Any clarification on the license, though? I went with the safe choice of LGPL-2.1-only for now, but if this code is licensed in an -or-later fashion, I'd like to represent that correctly.

**Comment by grosjo** [comment]
Choose the licence that makes most sense

I did this based on my own need and happy to share it to everybody wiht the same need. Everything else is not really important to me, so if LGPL-2.1 is ok, then it is ok

**Comment by neverpanic** [comment]
I'll leave it at LGPL-2.1-only then, that's probably the most accurate representation for now. If somebody downstream wants a different license, they can always approach you about it later. Thank you for the answers!
