### ISSUE TITLE
Ngram logic

### ISSUE THREAD

**Issue by ahmeij** [grosjo/fts-xapian#20]
After a relatively easy install the fts search seems to work perfectly, loving the files in the user folders forgoing the bulky databases of solr.

Although we use the exact configuration as shown in the readme searching on partial words does not seem to work, did we miss a piece of configuration?

When for example searching for 'Team' this finds an email, searching for 'eam' does not, same goes for names in the 'to' header, although the readme suggests that this should be possible.

Is there (more) configuration for this behaviour?

**Comment by grosjo** [comment]
Hi, what is your email client ?

**Comment by ahmeij** [comment]
Hi, initial tests are being done from Roundcube 1.3

**Comment by grosjo** [comment]
ok, I am using also roundcube without issues so problem is not there




can you copy the lines in the logs when you search for "eam" . The actual 
request shall appears in the logs (and the number of results)

**Comment by grosjo** [comment]
Have you also verified that all indexes are generated (i.e. "doveadm index -A -q \*" has done its job) ? (you can check the status by typing "ps aux | grep dovecot" and lookng for indexing requests)

**Comment by ahmeij** [comment]
Sorry I missed the notification. 

Apparently the indexing wasn't complete yet (on the test server with only a few accounts). Searching now works fast and complete!

Thank you for the help and the plugin.
