### ISSUE TITLE
Indexer-worker dying with SIGSEGV upon doveadm indexing

### ISSUE THREAD

**Issue by dejanstrbac** [grosjo/fts-xapian#22]
Hi,
Thank you for the plugin! I am trying to get it running but continuously get the indexing worker killed. Have you maybe seen such issue before? Nothing special in my setup, have latest dovecot (2.3.6), xapian 1.4.11 and git master of fts-xapian, standard dovecot setup, 2 GB vsz limit on the worker and I get:

Jul 11 13:04:45 indexer: Error: Indexer worker disconnected, discarding 1 requests for dejan@strbac.me
Jul 11 13:04:45 indexer-worker(dejan@strbac.me)<1341><O2hQBe0zJ109BQAAJ/KIYg>: Fatal: master: service(indexer-worker): child 1341 killed with signal 11 (core dumps disabled - https://dovecot.org/bugreport.html#coredumps)

**Comment by dejanstrbac** [comment]
I am running Slackware 14.2, just seen you had such issue on older Ubuntu.

**Comment by grosjo** [comment]
Can you please send the coredump (gdb) ?

**Comment by grosjo** [comment]
> I am running Slackware 14.2, just seen you had such issue on older Ubuntu.

Yes, and a simple upgrade of a buggy stdlibc solved the problem. Maybe can you try updating our system ?

**Comment by jpoonj** [comment]
My indexer-worker segfaults were solved with an updated libicu which also required an updated gcc.  CentOS7 will segfault with libicu-50.1.2-17.el7.x86_64.

Indexing is working with libicu 64.2 and gcc 9.2.0.
