### ISSUE TITLE
Static analyzer issues in your code

### ISSUE THREAD

**Issue by cmouse** [grosjo/fts-xapian#3]
fts-xapian version: 29fa9996bf160c6f8523952190b9300825f6ee5a

Please see https://cmouse.fi/scan-build-2019-01-14-18-20-31-868992-E4dUmu/

**Comment by cmouse** [comment]
Those strlcpy ones can be easily avoided by using dovecot's string_t (see src/lib/str.h), or c++ stringbuilder.

**Comment by grosjo** [comment]
I fixed the memory leak identified by your tool

**Comment by cmouse** [comment]
It's actually clang's scan-build, not mine

**Comment by grosjo** [comment]
ok cool. Can you rerun the tool ?

**Comment by cmouse** [comment]
Yeah, memory leak is gone..

**Comment by grosjo** [comment]
:+1:
