### ISSUE TITLE
ICU 64 requirement

### ISSUE THREAD

**Issue by LaurensVanAcker** [grosjo/fts-xapian#34]
Hi

Is the ICU v64 requirement necessary?
The HOWTO mentions "_apt-get install libicu-dev_", but Ubuntu is using v63 at the moment: https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=libicu-dev&searchon=names

```python
checking pkg-config is at least version 0.25... yes
checking for ICU_UC... no
checking for ICU_I18N... no
configure: error: icu 64 or higher is required, but was not found.
```

**Comment by slavkoja** [comment]
see #31

**Comment by LaurensVanAcker** [comment]
Thanks, I changed **>=64** to **>=63** and he is indexing all mails now.

**Comment by grosjo** [comment]
If there is no issue with 63, I will change the requirement down

**Comment by grosjo** [comment]
If there is no issue with 63, I will change the requirement down

**Comment by slavkoja** [comment]
@LaurensVanAcker  BTW, if you are interested, i have debian package for it, the `debian` directory you can find here https://git.slavino.sk/mojrepo.git/tree/testing/dovecot-xapian and the package for stable is here https://debs.slavino.sk/pool/main/d/dovecot-xapian/ (beware, not tested yet)

**Comment by LaurensVanAcker** [comment]
That's interesting, thanks for the tip! Is the Debian package updated manual or automatically on GIT pushes? You should add it to the Ubuntu default apt index?
I can confirm it's running perfectly with v63. It indexed years of mails and I can search Dutch terms using Roundcube and BlueMail.

**Comment by slavkoja** [comment]
IMO, here is not proper place to discuss my repo ;-)

**Comment by LaurensVanAcker** [comment]
You are right. I can confirm it's running perfectly with v63. It indexed years of mails and I can search Dutch terms using Roundcube and BlueMail. I'm closing this issue as a commit already exists to fix this issue.

**Comment by Jean-Daniel** [comment]
Can we now why v64 was chosen in the first place. I was running the plugin flawlessly on Ubuntu 18.04 LTS for some times (ICU 60) without any issue, but now I can't upgrade due to this new requirement.

Note: Switching back to v60 in the configure script let me built it without issue.

**Comment by grosjo** [comment]
> Can we now why v64 was chosen in the first place. I was running the plugin flawlessly on Ubuntu 18.04 LTS for some times (ICU 60) without any issue, but now I can't upgrade due to this new requirement.
> 
> Note: Switching back to v60 in the configure script let me built it without issue.

Because I was not able to test it on old releases (my servers are on Archlinux, using latest versions)

**Comment by grosjo** [comment]
@Jean-Daniel  Can you confirm 60 is good enough in production use ?
