### ISSUE TITLE
More details about memory limits

### ISSUE THREAD

**Issue by slavkoja** [grosjo/fts-xapian#39]
Please, can you provide more details about memory requirements? I expect that this will depend on mailbox or/and message sizes, but i do not know.

I consider changing `default_vsz_limit` as problematic, because this will affect all services, which has not own limits and this can be quite lot (8 times more than default). Or i am wrong?

Is/is not possible to raise this limit for indexer only?

**Comment by grosjo** [comment]
I dont think dovecot allow such parameter

@cmouse : Any clue on this ?

@slavkoja : Can you try lower values and check the log file for memory outage on a test server ?

**Comment by slavkoja** [comment]
I tried it with default memory limit (256M) without issue:
```
indexer-worker(slavko@example.org)<12589><OIYBE6H+Tl4tMQAAAzoamQ>: Indexed 0 messages in Drafts
indexer-worker(ferino@example.org)<12588><cF0pE6H+Tl4sMQAAAzoamQ>: Indexed 0 messages in INBOX
indexer-worker(slavko@example.org)<12589><YHKQFaH+Tl4tMQAAAzoamQ>: Indexed 0 messages in Trash
indexer-worker(over@example.org)<12587><kN5fE6H+Tl4rMQAAAzoamQ>: Indexed 2 messages in INBOX (UIDs 1..2)
indexer-worker(slavko@example.org)<12589><uMiDGaH+Tl4tMQAAAzoamQ>: Indexed 32 messages in INBOX (UIDs 22..53)
```
but my test server is really small in all dimensions, even messages are small:
```du -sh /srv/vmail/example.org/*
48K	/srv/vmail/example.org/ferino
1,5M	/srv/vmail/example.org/over
524K	/srv/vmail/example.org/slavko
```

**Comment by cmouse** [comment]
service indexer-worker {
  vsz_limit = 0
}

**Comment by grosjo** [comment]
@slavkoja  : works for you ?

**Comment by slavkoja** [comment]
I did not test it, but i see no reason to not work without limit, when it works with default limit and i am sure, that @cmouse know own software ;-)

IMO, do not suggest to touch the `default_vsz_limit` in README at all, it can be dangerous to have no limits by default if something will go bad. Once again, the dovecot's authors will know better why they have default value in it.

**Comment by cmouse** [comment]
The limits are there to avoid accidents. But they should be increased when necessary. You could also increase same limit for imap process, to, say 1-2G.

**Comment by grosjo** [comment]
WHen I do 
service indexer-worker {
vsz_limit = 0
}

my server complaint of "out of memory"

**Comment by cmouse** [comment]
https://doc.dovecot.org/configuration_manual/service_configuration/#vsz-limit

**Comment by igorzigorz** [comment]
Set the default default_vsz_limit = 0 is a bad idea. 
Set vsz_limit only for the indexer-worker it works fine.
256M is definitely not enough. 1-2G is ok for my configuration.
