### ISSUE TITLE
Building FTS-Xapian on CentOS 7

### ISSUE THREAD

**Issue by alessice** [grosjo/fts-xapian#40]
Hi,
I'm trying to build your plugin on Centos 7 and Dovecot 2.2.36 (build from source).

The first difficulty is to build Xapian 1.4.x but I'm looking for support on related mailing-list.

The second difficulty is to install libicu-60 since centos 7 is provided with libicu-50. The version 60 of ICU is mandatory or just because you are develop your plugin on debian where the libicu version is 60 by default?

Thanks

**Comment by alessice** [comment]
Hi,

I have successfully build xapian from source, and also ICU 66. I have found some issue to build fts-xapian because I have installed xapian under /opt/xapian/ but was unable to find a configure options for fts-xapian to said where is xapian-config so I rebuild xapian to install under /usr/local.

If possible please ask some configure options to fts-xapian like --with-xapian= and --with-icu= so we can install it under non standard locations.

Thanks

**Comment by grosjo** [comment]
Can you tell me what "pkg-config --cflags-only-I icu-uc icu-io icu-i18n" returns ?

**Comment by grosjo** [comment]
can you also test adding "export PATH=$PATH:/opt/xapian/" ?

**Comment by grosjo** [comment]
@alessice Shall I close the issue ?

**Comment by grosjo** [comment]
@alessice  PLease re-open if you need more help

**Comment by project0** [comment]
If someone else is facing the same issues (as i did): https://github.com/Project0/container-hub/blob/f3e55b04fb947f87bdcd963f986daee503fb60c8/images/dovecot/Dockerfile#L56-L72
btw. i was able to compile against icu 50

**Comment by grosjo** [comment]
@Project0 Can you clarify what needs to be updated or a PR if the case happen ?

**Comment by project0** [comment]
basically the ICU version dependency needs to be lowered down from 60 to 50. I could not find a issue yet.
