### ISSUE TITLE
Doesn't search for all folders

### ISSUE THREAD

**Issue by igorzigorz** [grosjo/fts-xapian#41]
dovecot 2.3.10 fts xapian 1.2.11a and roundcube 1.4.3
Several folders about 20Gb and 18000 messages.
Searching text for current folder or current with subfolders - no problem.
But not searching for all folders via web or doveadm.
"doveadm search" in the loop  for specific folder names is Ok.
But "doveadm search mailbox \* body sometext" or "doveadm search body sometext"  outputs almost all messages.

**Comment by grosjo** [comment]
This is a dovecot design. fts-xapian is just the backffice. You may post your issue on the dovecot mailing list

**Comment by igorzigorz** [comment]
But why does fts-lucene have a different behavior? Works as expected.

**Comment by grosjo** [comment]
Can you share your dovecot conf ?

**Comment by igorzigorz** [comment]
doveconf -n

[lucene.txt](https://github.com/grosjo/fts-xapian/files/4387445/lucene.txt)
[xapian.txt](https://github.com/grosjo/fts-xapian/files/4387447/xapian.txt)

**Comment by grosjo** [comment]
can you try issuing the same commands from /tmp (to avoid conflicting "*" with local folders) ?

**Comment by igorzigorz** [comment]
doveadm search -u user mailbox '*' body 'sometext'
doveadm search -u user body 'sometext'
In any place the same result. This is when fts-lucene is enabled.

**Comment by grosjo** [comment]
In deed, I need to implement the "_multi" function according to dovecot specs.
Will do this weekend

**Comment by grosjo** [comment]
Please try with latest git

**Comment by igorzigorz** [comment]
Now the search is the same with or without a mailbox.
But different results if the query "text" or "body". Looking for a unique string.
doveadm search -u user body 'sometext' is correct, one message.
But doveadm search -u user text 'sometext' finds multiple messages.

**Comment by grosjo** [comment]
"body" search in the message body
"text" search in the whole fields (including title, from, to, ..)

**Comment by igorzigorz** [comment]
fts-lucene again works as expected.
This is a really unique string for all messages.

**Comment by igorzigorz** [comment]
Ok, I'm trying to find a string that isn't exactly there (sha384 /etc/resolv.conf).
doveadm search -u user text 'thisstring' found 31 messages.

**Comment by grosjo** [comment]
Can you clarify what exactly is "as exptected" and what is wrong currently, with an example ? (output of the commands)

**Comment by igorzigorz** [comment]
"as exptected" - relevant to the grep search. If I have a single message with some unique string then the search returns only one message. Not important "text" or " body". And if there is no such string, then nothing.

**Comment by grosjo** [comment]
Ok
So what is the actual issue with fts-xapian ?

**Comment by igorzigorz** [comment]
Search seems fine now.
In general, there was a problem with roundcube and moving a large number of messages and renaming folders. Before that, moving worked, but with error messages. Due to starting indexing.
Now indexing does not start at all.
Investigating the problem.

**Comment by grosjo** [comment]
I tested renaming folders with roundcube, the index is kept (no re-indexing)
Moving large number of items is creating timeouts in roundcube in deed, but the architecture shall be dsicussed with dovecot.
Let me know if something else seems broken

**Comment by igorzigorz** [comment]
Rechecked, all seem ok now. This issue can be closed.

**Comment by grosjo** [comment]
ok cool
