### ISSUE TITLE
Index needs positional data?

### ISSUE THREAD

**Issue by Nimloth** [grosjo/fts-xapian#45]
When compared to fts_lucene, I found the fts_xapian plugin to generate way bigger index files.
Looking at the code of the plugin, I noticed that the index_text() method is used.
This stores positional data (for phrase searching). I may be wrong, but should that not be irrelevant in the context of IMAP searches? (If not, I'd be grateful if you pointed me to the relevant RFC(s)).
At any rate, if positional data were not needed, you could use the index_text_without_positions() method instead of index_text() which should decrease the index size significantly (and probably the indexing time, too).

**Comment by Nimloth** [comment]
Hm, I seem to be wrong. The position.glass databases are seemingly not filled with any data. I don't see how, though, as that should be the behaviour of index_text().
At any rate, the index sizes are rather huge despite this fact.
Is it usual for the xapian indexes to require several times the space of lucene indexes? Do you have information on the expected size of the index in comparison with the mailbox?

**Comment by Nimloth** [comment]
To give an example: A mailbox of 1.8 GB resulted in a lucene index of just 17 MB (0.92% of the mailbox size), whereas the xapian index ended up being a whopping 340 MB (18.45% of the mailbox size).

**Comment by grosjo** [comment]
IMHO, you shall compare fts-xapian with fts-squat, as the approach to indexing is different from lucene

This plug-in does not directly deal with glass files but the Xapian library does. The only driver is the parameters used in calling the Xapian function. If you have good expertise of Xapian, do not hesistate to suggest changes or make a PR.

I removed recently a bug where the trashed emails where kept in index instead of being removed. Are you using latest git ?

**Comment by Nimloth** [comment]
I only used xapian once in a project and there I had the issue of the positional data adding a lot of bloat, which is why I jumped to conclusions here.

I really like the approach of using a library as opposed to a client-server solution for search: I prefer to reduce the amount of components I have to monitor.

So far, I was using version 1.2.1 of the plugin - I'll upgrade and see if that helps.
Thank you!

**Comment by grosjo** [comment]
@Nimloth How is it going with git version ?

**Comment by Nimloth** [comment]
@grosjo The new version works well and it seems that some mailbox' indices were shrunk by running optimize. But the ratio of mailbox size : index size is roughly the same as in my example.
Since it seems this is not due to any issue with the plugin, but rather how xapian works, I guess you can close this issue?
And: Thanks again for your work!

**Comment by SerialVelocity** [comment]
@Nimloth Thanks for filing this! I just tried switching to fts-xapian and encountered the same huge index. Back to fts-solr I go!
