### ISSUE TITLE
 Error: FTS Xapian: Unknown header 'message-id'

### ISSUE THREAD

**Issue by trentbuck** [grosjo/fts-xapian#46]
(first time using github's BTS, so apologies if I screw up)

I switched a prod server from solr to xapian yesterday, and now two specific searches are failing.

One appears in syslog:

    Error: FTS Xapian: Unknown header 'message-id'

The other is coming from cron jobs that do something like

    doveadm move Trash mailbox Archives header list-id rnd-announce.googlegroups.com SUBJECT '...' before 7d

AFAICT both of these have the same cause: fts-xapian only indexes specific headers, and Message-ID is omitted (due to a typo) and List-ID is omitted (due to lack of interest).

https://github.com/grosjo/fts-xapian/blob/master/src/fts-backend-xapian.cpp#line=20

I suggest the following actions:

 1. double-check if hdsr_email should have "messageid" or "message-id".
 2. document in the README.md that only some headers are indexed.
 3. add list-id, maybe?  (might be too expensive in terms of xapian-index disk size?)
 4. make the list of headers configurable? (might be too expensive in terms of maintenance burden?)
 5. help me work out what I can do in the meantime.  Is turning off fts_enforced=yes sufficient?  I am a little nervous to try that because "doveadm index" is still busy indexing the backlog of existing mail (about 200G).

I am using Debian 10 with dovecot 2.3.4.1-5+deb10u2 and fts-xapian 1.3.1-0~twb2 (my packaging, see https://bugs.debian.org/921634)

**Comment by grosjo** [comment]
The headers are "cleaned" of '-´  and other symboles, therefore 'messageid' (without '-') is correct

Also the "unknown header" was an 'error' in previous release, but transformed into a simple warning in 1.3.1.  

Can you share the source email (at least the headers) creating this ?

Adding list-id is not using any resource as rarely used.

**Comment by trentbuck** [comment]
Short version: I don't know which email triggered the error message.  I will try to find out.


Detailed version follows.

Joan Moreau wrote:
> The headers are "cleaned" of '-´  and other symboles, therefore 'messageid' (without '-') is correct

OK, that makes sense.
(I vaguely remembered that but did not find the actual code when I was writing the bug report.)

> Also the "unknown header" was an 'error' in previous release, but transformed into a simple warning in 1.3.1.

I think there are two different messages, and only the second one was changed recently (from warning to info)?

    $ git grep 'Unknown header' 1.3.1
    1.3.1:src/fts-backend-xapian-functions.cpp:                     i_error("FTS Xapian: Unknown header '%s'",h2);
    1.3.1:src/fts-backend-xapian.cpp:               if(verbose>1) i_info("FTS Xapian: Unknown header '%s'",ctx->tbi_field);

The "Error" in my report is exactly from the logs:

    cyber@debian:~$ journalctl -b0 --since='6h ago' -u dovecot -oshort-iso -p4 | grep 'Unknown header'
    [...]
    2020-06-02T08:39:08+1000 debian.organictrader.net.au dovecot[2810]: imap(claire)<18062><k758dg2nwfV5LEHa>: Error: FTS Xapian: Unknown header 'message-id'
    2020-06-02T08:39:08+1000 debian.organictrader.net.au dovecot[2810]: imap(claire)<18062><k758dg2nwfV5LEHa>: Error: FTS Xapian: Unknown header 'message-id'
    2020-06-02T08:39:08+1000 debian.organictrader.net.au dovecot[2810]: imap(claire)<18062><k758dg2nwfV5LEHa>: Error: FTS Xapian: Unknown header 'message-id'
    2020-06-02T08:39:08+1000 debian.organictrader.net.au dovecot[2810]: imap(claire)<18062><k758dg2nwfV5LEHa>: Error: FTS Xapian: Unknown header 'message-id'
    2020-06-02T08:39:08+1000 debian.organictrader.net.au dovecot[2810]: imap(claire)<18062><k758dg2nwfV5LEHa>: Error: FTS Xapian: Unknown header 'message-id'
    2020-06-02T08:39:08+1000 debian.organictrader.net.au dovecot[2810]: imap(claire)<18062><k758dg2nwfV5LEHa>: Error: FTS Xapian: Unknown header 'message-id'
    2020-06-02T09:50:07+1000 debian.organictrader.net.au dovecot[2810]: imap(sam)<18877><sdNbdA6nRpcKAALP>: Error: FTS Xapian: Unknown header 'message-id'
    2020-06-02T09:50:07+1000 debian.organictrader.net.au dovecot[2810]: imap(sam)<18877><sdNbdA6nRpcKAALP>: Error: FTS Xapian: Unknown header 'message-id'
    2020-06-02T09:50:07+1000 debian.organictrader.net.au dovecot[2810]: imap(sam)<18877><sdNbdA6nRpcKAALP>: Error: FTS Xapian: Unknown header 'message-id'
    2020-06-02T09:50:07+1000 debian.organictrader.net.au dovecot[2810]: imap(sam)<18877><sdNbdA6nRpcKAALP>: Error: FTS Xapian: Unknown header 'message-id'
    2020-06-02T09:50:07+1000 debian.organictrader.net.au dovecot[2810]: imap(sam)<18877><sdNbdA6nRpcKAALP>: Error: FTS Xapian: Unknown header 'message-id'
    2020-06-02T09:50:07+1000 debian.organictrader.net.au dovecot[2810]: imap(sam)<18877><sdNbdA6nRpcKAALP>: Error: FTS Xapian: Unknown header 'message-id'
    2020-06-02T09:50:07+1000 debian.organictrader.net.au dovecot[2810]: imap(sam)<18877><sdNbdA6nRpcKAALP>: Error: FTS Xapian: Unknown header 'message-id'
    2020-06-02T09:50:07+1000 debian.organictrader.net.au dovecot[2810]: imap(sam)<18877><sdNbdA6nRpcKAALP>: Error: FTS Xapian: Unknown header 'message-id'

I am confident that I am running 1.3.1:

    cyber@debian:~$ dpkg-query -W dovecot-fts-xapian
    dovecot-fts-xapian      1.3.1-0~twb2

    cyber@debian:~$ strings /usr/lib/dovecot/modules/lib21_fts_xapian_plugin.so | grep -F 1.3
    CXXABI_1.3.1
    CXXABI_1.3

    cyber@debian:~$ strings /usr/lib/dovecot/modules/lib21_fts_xapian_plugin.so | grep -F CXXABI
    CXXABI_1.3.1
    CXXABI_1.3

> Can you share the source email (at least the headers) creating this ?

I do not have a specific email handy, because
these logs came from dovecot-index's background indexing of existing (large!) mailboxes.

I will see if I can generate the same behaviour with a test IMAP folder with only a few emails.

For what it is worth, the previous solr config did not log similar messages
(but it's possible solr was broken, but users were not complaining).
Below is EXACTLY the config changes I made that day.
Sorry about the SSL/DH noise -- that is cleaning up after a Debian upgrade a few months ago.

    cyber@debian:/etc$ sudo env GIT_PAGER=cat git log -p --since=2020-05-01 -- dovecot
    commit 0ff057ada1033e4318dcc4e057bfe20542923e6b
    Author: REDACTED
    Date:   Thu May 28 22:24:40 2020 +1000

        daily autocommit

    diff --git a/dovecot/conf.d/90-plugin.conf b/dovecot/conf.d/90-plugin.conf
    index e7075daa..1c8233c2 100644
    --- a/dovecot/conf.d/90-plugin.conf
    +++ b/dovecot/conf.d/90-plugin.conf
    @@ -18,6 +18,7 @@

     ## This is the version using third-party fts-xapian.

    +# https://doc.dovecot.org/settings/plugin/fts-plugin/#fts-plugin
     # https://wiki2.dovecot.org/Plugins/FTS
     # https://github.com/grosjo/fts-xapian
     # http://bugs.debian.org/921634
    @@ -29,6 +30,7 @@ plugin {
       fts_enforced = yes
       fts_autoindex_exclude = \Junk
       fts_autoindex_exclude2 = \Trash
    +  fts_autoindex_exclude3 = \crm-spam
       fts_autoindex_max_recent_msgs = 100
     }
     service decode2text {
    @@ -38,3 +40,8 @@ service decode2text {
         mode = 0666
       }
     }
    +
    +# https://github.com/grosjo/fts-xapian/issues/39
    +service indexer-worker {
    +  vsz_limit = 2 G
    +}

    commit 5930346d387eb32975fc89d7857698777d8ff1cb
    Author: Jason Lewis <jason@dickson.st>
    Date:   Tue May 26 22:23:58 2020 +1000

        daily autocommit

    diff --git a/dovecot/conf.d/10-mail.conf b/dovecot/conf.d/10-mail.conf
    index e03d7301..20190c59 100644
    --- a/dovecot/conf.d/10-mail.conf
    +++ b/dovecot/conf.d/10-mail.conf
    @@ -198,7 +198,9 @@ namespace inbox {

     # Space separated list of plugins to load for all services. Plugins specific to
     # IMAP, LDA, etc. are added to this list in their own .conf files.
    -mail_plugins = fts fts_solr
    +#mail_plugins = fts fts_solr
    +mail_plugins = fts fts_xapian
    +

     ##
     ## Mailbox handling optimizations
    diff --git a/dovecot/conf.d/10-ssl.conf b/dovecot/conf.d/10-ssl.conf
    index 0de70533..df154719 100644
    --- a/dovecot/conf.d/10-ssl.conf
    +++ b/dovecot/conf.d/10-ssl.conf
    @@ -30,10 +30,11 @@ ssl_key = </etc/letsencrypt/live/imap.organictrader.com.au/privkey.pem
     #ssl_require_crl = yes

     # Directory and/or file for trusted SSL CA certificates. These are used only
    -# when Dovecot needs to act as an SSL client (e.g. imapc backend). The
    -# directory is usually /etc/ssl/certs in Debian-based systems and the file is
    -# /etc/pki/tls/cert.pem in RedHat-based systems.
    -#ssl_client_ca_dir =
    +# when Dovecot needs to act as an SSL client (e.g. imapc backend or
    +# submission service). The directory is usually /etc/ssl/certs in
    +# Debian-based systems and the file is /etc/pki/tls/cert.pem in
    +# RedHat-based systems.
    +ssl_client_ca_dir = /etc/ssl/certs
     #ssl_client_ca_file =

     # Request client to send a certificate. If you also want to require it, set
    @@ -45,17 +46,33 @@ ssl_key = </etc/letsencrypt/live/imap.organictrader.com.au/privkey.pem
     # auth_ssl_username_from_cert=yes.
     #ssl_cert_username_field = commonName

    -# DH parameters length to use.
    -#ssl_dh_parameters_length = 1024
    +# SSL DH parameters
    +# Generate new params with `openssl dhparam -out /etc/dovecot/dh.pem 4096`
    +# Or migrate from old ssl-parameters.dat file with the command dovecot
    +# gives on startup when ssl_dh is unset.
    +ssl_dh = </etc/dovecot/dh.pem

    -# SSL protocols to use
    -#ssl_protocols = !SSLv2
    +# Minimum SSL protocol version to use. Potentially recognized values are SSLv3,
    +# TLSv1, TLSv1.1, and TLSv1.2, depending on the OpenSSL version used.
    +#ssl_min_protocol = TLSv1

    -# SSL ciphers to use
    -#ssl_cipher_list = ALL:!LOW:!SSLv2:!EXP:!aNULL
    +# SSL ciphers to use, the default is:
    +#ssl_cipher_list = ALL:!kRSA:!SRP:!kDHd:!DSS:!aNULL:!eNULL:!EXPORT:!DES:!3DES:!MD5:!PSK:!RC4:!ADH:!LOW@STRENGTH
    +# To disable non-EC DH, use:
    +#ssl_cipher_list = ALL:!DH:!kRSA:!SRP:!kDHd:!DSS:!aNULL:!eNULL:!EXPORT:!DES:!3DES:!MD5:!PSK:!RC4:!ADH:!LOW@STRENGTH
    +
    +# Colon separated list of elliptic curves to use. Empty value (the default)
    +# means use the defaults from the SSL library. P-521:P-384:P-256 would be an
    +# example of a valid value.
    +#ssl_curve_list =

     # Prefer the server's order of ciphers over client's.
     #ssl_prefer_server_ciphers = no

     # SSL crypto device to use, for valid values run "openssl engine"
     #ssl_crypto_device =
    +
    +# SSL extra options. Currently supported options are:
    +#   compression - Enable compression.
    +#   no_ticket - Disable SSL session tickets.
    +#ssl_options =
    diff --git a/dovecot/conf.d/90-plugin.conf b/dovecot/conf.d/90-plugin.conf
    index f99673fe..e7075daa 100644
    --- a/dovecot/conf.d/90-plugin.conf
    +++ b/dovecot/conf.d/90-plugin.conf
    @@ -6,12 +6,35 @@
     # settings take effect. See <doc/wiki/Plugins.txt> for list of plugins and
     # their configuration. Note that %variable expansion is done for all values.

    +## This is the version using first-party solr.
    +# plugin {
    +#   #setting_name = value
    +#   fts = solr
    +#   fts_solr = url=http://10.0.2.19:8080/solr/
    +#   fts_autoindex = yes
    +#   # If FTS fails, don't silently fall back to slow "kill the server with I/O" mode.
    +#   fts_enforced = yes
    +# }
    +
    +## This is the version using third-party fts-xapian.
    +
    +# https://wiki2.dovecot.org/Plugins/FTS
    +# https://github.com/grosjo/fts-xapian
    +# http://bugs.debian.org/921634
     plugin {
    -  #setting_name = value
    -  fts = solr
    -  fts_solr = url=http://10.0.2.19:8080/solr/
    +  fts = xapian
    +  fts_xapian = partial=2 full=20
    +  fts_decoder = decode2text
       fts_autoindex = yes
    -
    -  # If FTS fails, don't silently fall back to slow "kill the server with I/O" mode.
       fts_enforced = yes
    +  fts_autoindex_exclude = \Junk
    +  fts_autoindex_exclude2 = \Trash
    +  fts_autoindex_max_recent_msgs = 100
    +}
    +service decode2text {
    +  executable = script /usr/share/doc/dovecot-core/examples/decode2text.sh
    +  user = dovecot
    +  unix_listener decode2text {
    +    mode = 0666
    +  }
     }
    diff --git a/dovecot/dh.pem b/dovecot/dh.pem
    new file mode 100644
    index 00000000..22e83c32
    --- /dev/null
    +++ b/dovecot/dh.pem
    @@ -0,0 +1,5 @@
    [REDACTED]

I had a quick look and the only error messages from fts_solr are when solr crashes/hangs.

    cyber@debian:~$ xzgrep -hFw fts_solr /var/log/mail.err* | sort | tail
    [...]
    2020-05-26T00:06:30.465268+10:00 debian dovecot: imap(ar)<28257><h2PrLHKmRdIKAAJl>: Error: fts_solr: Indexing failed: Request timed out (Request queued 180.308 secs ago, 2 times retried, 3 send attempts in 180.175 secs, 60.049 in last attempt, 60.050 in http ioloop, 0.000 in other ioloops, connected 60.050 secs ago)
    2020-05-26T00:09:21.582844+10:00 debian dovecot: imap(ar)<28257><h2PrLHKmRdIKAAJl>: Error: fts_solr: Indexing failed: 503  (2 retries in 171.115 secs)

solr's own logs (in /var/log/tomcat8) are horrible java gibberish, but
I did find /etc/solr/schema.xml which is straight from dovecot and DOES NOT index List-ID:

    cyber@jasmine:/etc/solr$ cksum conf/schema.xml
    3565382739 2953 conf/schema.xml

    cyber@jasmine:/etc/solr$ curl -sL https://github.com/dovecot/core/raw/81b5b188c478ec36bea8bda8fcad1e5f32ac612b/doc/solr-schema.xml | cksum
    3565382739 2953

So I am confused -- was the user's "doveadm move" command broken for
years, or was fts_solr behaving differently to fts_xapian --
DESPITE both having fts_enforced=yes and NEITHER being told to index List-ID?

> Adding list-id is not using any resource as rarely used.

Cool.  I will learn how to do a github-style pull request, I guess :-)
I've attached a test patch, to see if github auto-detects it.

**Comment by grosjo** [comment]
Please kindly check latest git

**Comment by trentbuck** [comment]
Joan Moreau wrote:
> Please kindly check latest git

Hi, I tested 1.3.1-4-g954d79b and I think this is fixed.

This completed without error (i.e. List-ID is working):

    sudo -u jason USER=jason /usr/bin/doveadm move Archives mailbox inbox header list-id 'rnd-announce.googlegroups.com'  SUBJECT  '{RnD Announce} The space is now open' before 1d

I also see no Message-ID logs since upgrading fts-xapian, although that might just be coincidence.

I think #46 can be considered closed.
Thanks!
