### ISSUE TITLE
segfault when using doveadm fts rescan

### ISSUE THREAD

**Issue by fezie** [grosjo/fts-xapian#47]
When using "doveadm fts rescan" with current git version of fts-xapian it segfaults:
(I shortend the path in fpath a bit)

(gdb) bt
#0  __strchr_avx2 () at ../sysdeps/x86_64/multiarch/strchr-avx2.S:57
#1  0x00007f2c677ea4b0 in strstr (__needle=<synthetic pointer>, __haystack=0x1 <error: Cannot access memory at address 0x1>) at /usr/include/string.h:324
#2  fts_backend_xapian_empty_db (fpath=0x55b4549846c0 "[...]/Maildir/xapian-indexes", sb=<optimized out>, typeflag=1) at fts-backend-xapian-functions.cpp:1071
#3  0x00007f2c69e79653 in ftw_dir (data=data@entry=0x7ffc0bfcc080, st=0x7ffc0bfcc0e0, old_dir=old_dir@entry=0x0) at ../sysdeps/wordsize-64/../../io/ftw.c:501
#4  0x00007f2c69e79c5f in ftw_startup (dir=<optimized out>, is_nftw=is_nftw@entry=0, func=func@entry=0x7f2c677ea480 <fts_backend_xapian_empty_db(char const*, stat const*, int)>, 
    descriptors=descriptors@entry=512, flags=flags@entry=0) at ../sysdeps/wordsize-64/../../io/ftw.c:768
#5  0x00007f2c69e79fdf in ftw (path=<optimized out>, func=func@entry=0x7f2c677ea480 <fts_backend_xapian_empty_db(char const*, stat const*, int)>, descriptors=descriptors@entry=512)
    at ../sysdeps/wordsize-64/../../io/ftw.c:817
#6  0x00007f2c677e9ad3 in fts_backend_xapian_rescan (_backend=0x55b45497e910) at fts-backend-xapian.cpp:527
#7  0x00007f2c69cfa63d in fts_backend_rescan () from /usr/lib/dovecot/modules/lib20_fts_plugin.so
#8  0x00007f2c6739cd77 in ?? () from /usr/lib/dovecot/modules/doveadm/lib20_doveadm_fts_plugin.so
#9  0x000055b45480493f in ?? ()
#10 0x000055b454805756 in ?? ()
#11 0x000055b454806389 in doveadm_cmd_ver2_to_mail_cmd_wrapper ()
#12 0x000055b454816afd in doveadm_cmd_run_ver2 ()
#13 0x000055b454816b57 in doveadm_cmd_try_run_ver2 ()
#14 0x000055b4547f5b21 in main ()
(gdb) frame 2
#2  fts_backend_xapian_empty_db (fpath=0x55b4549846c0 "[...]/Maildir/xapian-indexes", sb=<optimized out>, typeflag=1) at fts-backend-xapian-functions.cpp:1071
1071			sl=strstr(sl,"/")+1;
(gdb) print sl
$3 = 0x1 <error: Cannot access memory at address 0x1>

**Comment by grosjo** [comment]
ok
can you try with changes I just made ?

**Comment by fezie** [comment]
thanks for the fast fix.
Yes it works now fine
