### ISSUE TITLE
Warning: Expunged message reappeared, giving a new UID

### ISSUE THREAD

**Issue by symphorien** [grosjo/fts-xapian#49]
Steps to reproduce: (I automated the test with a vm, it's 100% reproducible):

1. setup an alias multi@example.com -> "user1@example.com" "user2@example.com" with Postfix's `virtual_mailbox_aliases`
2. send an email to  multi@example.com
3. user1 uses fetchmail to fetch user1@example.com email

Result:
```
dovecot[933]: imap(user1@example.com)<1275><pT2xMlqrWOrAqAEB>: Warning: Maildir /var/vmail/example.com/user1: Expunged message reappeared, giving a new UID (old uid=1, file=1595778764.M920601P1261.server,S=920,W=945:2,)
```

If the alias only points to user1, or if xapian is disabled, or if user1 does not do step 3, then the warning disappears.

**Comment by symphorien** [comment]
It's possible to replace step 3 by:
```
doveadm expunge -u user1@example.com mailbox Inbox ALL
```

**Comment by grosjo** [comment]
Can you try doing the exact same test sending the email to user1@ ?

**Comment by symphorien** [comment]
No warning if the email is sent to user1@

**Comment by grosjo** [comment]
Have you tried with another FTS plugin (try squat, which is very similar , even if it is obsolete)

**Comment by grosjo** [comment]
Can you also put "verbose=2" in the dovecot.conf and send me the logs of the moment you send the email ?

**Comment by symphorien** [comment]
I attached the log.
[log.txt](https://github.com/grosjo/fts-xapian/files/5010599/log.txt)

The warning also happens with squat. I guess I should open the bug against dovecot then.

**Comment by grosjo** [comment]
If the bug exists also with other FTS engine, then the bug comes probably form core dovecot , indeed

**Comment by symphorien** [comment]
For reference, here is the email to the list: https://dovecot.org/pipermail/dovecot/2020-August/119575.html
