### ISSUE TITLE
scanelf: rpath_security_checks(): Security problem with relative DT_RUNPATH  ... lib21_fts_xapian_plugin.so

### ISSUE THREAD

**Issue by marcin-github** [grosjo/fts-xapian#50]
Hello!
Security checks inside portage (package manager in Gentoo) reports sec problem:
```
scanelf: rpath_security_checks(): Security problem with relative DT_RUNPATH '.' in /var/tmp/portage/net-mail/fts-xapian-1.3.2/image/usr/lib64/dovecot/lib21_fts_xapian_plugin.so
```

**Comment by grosjo** [comment]
@marcin-github Not sure what does it mean, and what operation are you doing.

Can you clarify how have you compiled the code and what operation are you doing ?

**Comment by grosjo** [comment]
@marcin-github any update ?

**Comment by grosjo** [comment]
Closing due to lack of answers
