### ISSUE TITLE
Indexing long lines uses a lot of memory

### ISSUE THREAD

**Issue by heytings** [grosjo/fts-xapian#53]
When a very long line is indexed by fts-xapian, the memory used by indexer-worker increases enormously and suddenly.
For example, with an email with a 40 KB long "To" field on a single line, the memory used suddenly increases by 100-150 MB, and about 15 seconds later by another 50 MB.
A simple workaround is to increase vsz_limit in dovecot.conf, as suggested in the dovecot log: "Out of memory (service indexer-worker { vsz_limit=256 MB }, you may need to increase it) - set CORE_OUTOFMEM=1 environment to get core dump)".

**Comment by grosjo** [comment]
Separating Base64 from a base64 word written intentionally by the writer is not feasable.
Indeed, increasing the memory is the very first solution. (I have default_vsz_limit = 0, and no issue at all) 
Further memory improvement will lead to further writes on Xapian DB, that will slow down enormously the indexing.
Do you see any other way ?

**Comment by heytings** [comment]
I'm sorry, but I don't understand your comment.

"Separating Base64 from a base64 word written intentionally by the writer is not feasable.": This issue is not about base64 words, but about normal words (names and email addresses) on a single long line.

"Indeed, increasing the memory is the very first solution. (I have default_vsz_limit = 0, and no issue at all)": If this is a comment about base64 words, then increasing the memory is a solution, but definitely not a good/robust one.  200 KB of base64 text creates a 100 MB database, and creating that database takes a very (very!) long time.

"Further memory improvement will lead to further writes on Xapian DB, that will slow down enormously the indexing.": I don't understand what you mean.

**Comment by grosjo** [comment]
Can you try with latest git , with "verbose=1" and let m know the log line with NGRAM keyword ?

**Comment by grosjo** [comment]
Any news ?

**Comment by grosjo** [comment]
@heytings Can you test with latest git, I found some memory leaks

**Comment by grosjo** [comment]
@heytings Please reopen if the problem remains
