### ISSUE TITLE
Problem with slow indexing

### ISSUE THREAD

**Issue by jave** [grosjo/fts-xapian#56]
I'm evaluating fts-xapian to see if I can use it instead of solr-fts.

At the moment indexing is very slow for me, and I'm would like to ask for advice regarding how to improve performance.

At the moment 8900/14948 messages have been indexed, in about 16 hours.

I run dovecot in a vm, with 8gb ram, and 8 cores. Mail is stored on nfs.

The vm doesnt seem to have too much load, about 4 gb is consumed, very little cpu.

indexing was started like this:
 sudo doveadm -Dv index -u joakim@verona.se '*'

I use this configuration:
plugin {
	plugin = fts fts_xapian

	fts = xapian
	fts_xapian = partial=2 full=20 attachments=0 verbose=0

	fts_autoindex = yes
	fts_enforced = yes
	
	fts_autoindex_exclude = \Trash
}

Any advice apreciated.

**Comment by grosjo** [comment]
Initial indexing is pretty slow indeed. You may put "partial=3" to speed up (partiel is the minimal onumber of characters indexed)
Are you using latest git ?

**Comment by grosjo** [comment]
Any news ?

**Comment by jave** [comment]
It is still very slow. At the moment im using partial=5.

**Comment by jave** [comment]
i recompiled from git just now

**Comment by grosjo** [comment]
you shall keep partial=3 at most 
/Initial/ indexing is slow indeed for exisiting large boxes.
Once initial indexing is done, then the indexing is a few ms per email

**Comment by grosjo** [comment]
@jave any update ?

**Comment by grosjo** [comment]
Can you try with latest git ?

**Comment by grosjo** [comment]
Please kindly re-open if you have any update on this

**Comment by jave** [comment]
sorry for late reply, fts-xapian hasnt worked for a while for me, so i havent tried it much. Ill report if I get back to it. Thanks!

**Comment by jwiegley** [comment]
I'm seeing terribly slow indexing as well. Using `partial=3`, and with a mailbox of about 175,000 messages, I finally gave up after waiting 3 full days.
