### ISSUE TITLE
Is it possible to change the location where indexes are stored?

### ISSUE THREAD

**Issue by basil-conto** [grosjo/fts-xapian#63]
Sorry if this is a naive question, but is it possible to change the location of the `xapian-indexes` subdirectories?

The reason I'm wondering is because they seem to confuse my current `mbsync` setup.  I might be able to get `mbsync` to ignore them, but it would be nice to know whether I can simply move them out of its way instead.

Thanks for this great plugin!

**Comment by grosjo** [comment]
Have you tried the "INDEX" keyword in the mail_location of your dovecot.conf ?

reference : https://doc.dovecot.org/configuration_manual/mail_location/

**Comment by basil-conto** [comment]
> I might be able to get `mbsync` to ignore them, but it would be nice to know whether I can simply move them out of its way instead.

Turns out it was pretty simple to get `mbsync` to ignore the index subdirectories using the `SubFolders` option (1), so I don't need to change anything with Dovecot, and am therefore closing this issue.

(1): https://sourceforge.net/p/isync/mailman/message/37147678/

> Have you tried the "INDEX" keyword in the mail_location of your dovecot.conf ?

No, thanks for the pointer! I'll keep this in mind if I need to tweak things further.
