### ISSUE TITLE
Xapian-core AND xapian-bindings needed.

### ISSUE THREAD

**Issue by lxsinfo** [grosjo/fts-xapian#64]
As Prerequisites you mention:

* Dovecot 2.2.x (or above)
* Xapian 1.4.x (or above)
* ICU 60.x (or above)

It would be more clear to mention that you need xapian-core as well as xapian-bindings to get Xapian to work with (in this case) python.

**Comment by grosjo** [comment]
Hello

I do not really understand
What is "xapian-bindings" ? (is that a specific distribution package ?)
There is no Python involved, why do you refer to it ?

**Comment by lxsinfo** [comment]
On FreeBSD I have to install both:
xapian-bindings-1.4.17_1           =   up-to-date with index
xapian-core-1.4.17,1               =   up-to-date with index
else fts-xapian won't work. 
(When mailbox directories are opened with IMAP empty index files are created and in the log it keep on showing that 0 (zero) messages were added to the index)

**Comment by grosjo** [comment]
ok, I updated the Readme.md

**Comment by grosjo** [comment]
@lxsinfo ok for you ?

**Comment by lxsinfo** [comment]
Yes it is. (btw, I found this suggestion in the dovecot documentation, I think for the commercial FTS). If you are interested I will try to find that link)

**Comment by lxsinfo** [comment]
I found it: https://wiki.dovecot.org/HelpOnXapian

**Comment by slavkoja** [comment]
It is help for wiki (moin) indexing, unrelated to dovecot indexing itself...

**Comment by lxsinfo** [comment]
Be that as it may, on FreeBSD I need this to get xapian working.
