### ISSUE TITLE
Command ignores excluded folders

### ISSUE THREAD

**Issue by a16bitsysop** [grosjo/fts-xapian#65]
Using commands from the ReadMe with config:

part of config:
`fts_autoindex_exclude = \Trash`

command:
`doveadm index -A -q \*`

The trash folder is indexed as well even though it is exclude

**Comment by grosjo** [comment]
Maybe you should ask the dovecot mailing list at dovecot@dovecot.org because the plugins just indexes what is asked to be indexed by the core process, that core process is the one taking care of that configuration

**Comment by a16bitsysop** [comment]
Ok thanks, will try that.
