### ISSUE TITLE
cannot search BODY content

### ISSUE THREAD

**Issue by jranma** [grosjo/fts-xapian#66]
Using FTP-xapian version 1.4.6 on linux buster, Dovecot version 2.3.4.1

FTS Xapian is working fine on headers (From, to, subject...) , but doesn't seem to search (or index) body content. 

mail.log: Jan 30 13:49:44 HOSTNAME dovecot: imap(me@myserver.com)<38523><Wdocjh26cI0AAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: Query= body:"searchword"
doesnt show anything. 

 Query= from:"searchword" OR to:"searchword" OR cc:"searchword" OR subject:"searchword" works fine !

"searchword" is part of many emails. 

Dovecot config: 
```
plugin {

plugin = fts fts_xapian

        fts = xapian
        fts_xapian = partial=3 full=20 attachments=1 verbose=0

        fts_autoindex = yes
        fts_enforced = yes

        fts_autoindex_exclude = \Trash
        fts_autoindex_exclude = \Junk

}
```

**Comment by grosjo** [comment]
WOrking fine for the body here. Can you put "attachments=0" and try again ? Maybe there is a bug there

**Comment by jranma** [comment]
unfortunately, it does not change anything. Only headers content is returned. 

Here is the command I use to reindex mailboxes: `doveadm index -A -q \*`

I'v eset a cron every night: `/usr/bin/doveadm fts optimize -A >/dev/null 2>&1`

**Comment by grosjo** [comment]
Can you share the complete piece of log, with verbose=1
It shall look like :
```

Jan 30 15:34:26 gjserver dovecot[931536]: imap(jom@grosjo.net)<931931><uCwl2x+6Kqh/AAAB>: FTS Xapian: Starting with partial=2 full=20 attachments=0 verbose=1
Jan 30 15:34:26 gjserver dovecot[931536]: imap(jom@grosjo.net)<931931><uCwl2x+6Kqh/AAAB>: FTS Xapian: fts_backend_xapian_get_last_uid
Jan 30 15:34:26 gjserver dovecot[931536]: imap(jom@grosjo.net)<931931><uCwl2x+6Kqh/AAAB>: FTS Xapian: Get last UID of Hobbies/Tech (f1fdf110ec9bc14c375b0000d6a3092d) = 255665
Jan 30 15:34:26 gjserver dovecot[931536]: imap(jom@grosjo.net)<931931><uCwl2x+6Kqh/AAAB>: FTS Xapian: fts_backend_xapian_refresh
Jan 30 15:34:26 gjserver dovecot[931536]: imap(jom@grosjo.net)<931931><uCwl2x+6Kqh/AAAB>: FTS Xapian: fts_backend_xapian_release (refresh)
Jan 30 15:34:26 gjserver dovecot[931536]: imap(jom@grosjo.net)<931931><uCwl2x+6Kqh/AAAB>: FTS Xapian: Committed 'refresh' in 0 ms
Jan 30 15:34:26 gjserver dovecot[931536]: imap(jom@grosjo.net)<931931><uCwl2x+6Kqh/AAAB>: FTS Xapian: fts_backend_xapian_get_last_uid
Jan 30 15:34:26 gjserver dovecot[931536]: imap(jom@grosjo.net)<931931><uCwl2x+6Kqh/AAAB>: FTS Xapian: Get last UID of Hobbies/Tech (f1fdf110ec9bc14c375b0000d6a3092d) = 255665
Jan 30 15:34:26 gjserver dovecot[931536]: imap(jom@grosjo.net)<931931><uCwl2x+6Kqh/AAAB>: FTS Xapian: fts_backend_xapian_lookup
Jan 30 15:34:26 gjserver dovecot[931536]: imap(jom@grosjo.net)<931931><uCwl2x+6Kqh/AAAB>: FTS Xapian: Query= body:"searchword"
Jan 30 15:34:26 gjserver dovecot[931536]: imap(jom@grosjo.net)<931931><uCwl2x+6Kqh/AAAB>: FTS Xapian: 1 results in 0 ms
Jan 30 15:34:26 gjserver dovecot[931536]: imap(jom@grosjo.net)<931931><uCwl2x+6Kqh/AAAB>: Logged out in=274 out=1786 deleted=0 expunged=0 trashed=0 hdr_count=1 hdr_bytes=542 body_count=0 body_bytes=0
```

**Comment by jranma** [comment]
`Jan 30 16:43:35 saturne dovecot: master: Warning: Killed with signal 15 (by pid=43179 uid=0 code=kill)
Jan 30 16:43:35 saturne dovecot: imap(jul@NOSPAM.com)<43096><N/jC7x+6D7OZbXcp>: Server shutting down. in=834 out=31424 deleted=0 expunged=0 trashed=0 hdr_count=2 hdr_bytes=10204 body_count=1 body_bytes=10068
Jan 30 16:43:35 saturne dovecot: imap(jul@NOSPAM.com)<43096><N/jC7x+6D7OZbXcp>: FTS Xapian: Deinit /var/vmail/nospam.com/julien/Maildir/xapian-indexes)
Jan 30 16:43:35 saturne dovecot: master: Dovecot v2.3.4.1 (f79e8e7e4) starting up for imap, lmtp, sieve, pop3 (core dumps disabled)
Jan 30 16:43:36 saturne dovecot: imap-login: Login: user=<jul@NOSPAM.com>, method=PLAIN, rip=153.109.119.41, lip=91.134.140.163, mpid=43210, TLS, session=<wKfh+x+6tLmZbXcp>
Jan 30 16:43:36 saturne dovecot: imap(jul@NOSPAM.com)<43210><wKfh+x+6tLmZbXcp>: FTS Xapian: Starting with partial=3 full=20 attachments=0 verbose=1
Jan 30 16:43:36 saturne dovecot: imap(jul@NOSPAM.com)<43210><wKfh+x+6tLmZbXcp>: Logged out in=52 out=596 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
Jan 30 16:43:36 saturne dovecot: imap(jul@NOSPAM.com)<43210><wKfh+x+6tLmZbXcp>: FTS Xapian: Deinit /var/vmail/nospam.com/julien/Maildir/xapian-indexes)
Jan 30 16:43:37 saturne dovecot: imap-login: Login: user=<jul@NOSPAM.com>, method=PLAIN, rip=::1, lip=::1, mpid=43212, TLS, session=<ALbu+x+6+KQAAAAAAAAAAAAAAAAAAAAB>
Jan 30 16:43:37 saturne dovecot: imap(jul@NOSPAM.com)<43212><ALbu+x+6+KQAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: Starting with partial=3 full=20 attachments=0 verbose=1
Jan 30 16:43:37 saturne dovecot: imap(jul@NOSPAM.com)<43212><ALbu+x+6+KQAAAAAAAAAAAAAAAAAAAAB>: Logged out in=149 out=1118 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
Jan 30 16:43:37 saturne dovecot: imap(jul@NOSPAM.com)<43212><ALbu+x+6+KQAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: Deinit /var/vmail/nospam.com/julien/Maildir/xapian-indexes)
Jan 30 16:43:44 saturne dovecot: imap-login: Login: user=<jul@NOSPAM.com>, method=PLAIN, rip=::1, lip=::1, mpid=43215, TLS, session=<CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43215><CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: Starting with partial=3 full=20 attachments=0 verbose=1
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43215><CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: fts_backend_xapian_get_last_uid
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43215><CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: Get last UID of INBOX (2aa527066a110c6083c20000f2488b2e) = 346
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43215><CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: fts_backend_xapian_refresh
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43215><CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: fts_backend_xapian_release (refresh)
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43215><CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: Committed 'refresh' in 1 ms
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43215><CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: fts_backend_xapian_get_last_uid
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43215><CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: Get last UID of INBOX (2aa527066a110c6083c20000f2488b2e) = 346
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43215><CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: fts_backend_xapian_lookup
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43215><CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: Query= body:"paroisse"
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43215><CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: 0 results in 1 ms
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43215><CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>: Logged out in=153 out=1513 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43215><CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: Deinit /var/vmail/nospam.com/julien/Maildir/xapian-indexes)
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43215><CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: fts_backend_xapian_release (unset_box)
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43215><CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: Committed 'unset_box' in 1 ms
Jan 30 16:43:44 saturne dovecot: imap-login: Login: user=<jul@NOSPAM.com>, method=PLAIN, rip=153.109.119.41, lip=91.134.140.163, mpid=43216, TLS, session=<OlFi/B+647mZbXcp>
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43216><OlFi/B+647mZbXcp>: FTS Xapian: Starting with partial=3 full=20 attachments=0 verbose=1
Jan 30 16:43:45 saturne dovecot: imap-login: Login: user=<jul@NOSPAM.com>, method=PLAIN, rip=153.109.119.41, lip=91.134.140.163, mpid=43218, TLS, session=<z1Vz/B+657mZbXcp>
Jan 30 16:43:45 saturne dovecot: imap(jul@NOSPAM.com)<43218><z1Vz/B+657mZbXcp>: FTS Xapian: Starting with partial=3 full=20 attachments=0 verbose=1
Jan 30 16:43:47 saturne dovecot: imap-login: Login: user=<jul@NOSPAM.com>, method=PLAIN, rip=::1, lip=::1, mpid=43220, TLS, session=<Xh+N/B+6CqUAAAAAAAAAAAAAAAAAAAAB>
Jan 30 16:43:47 saturne dovecot: imap(jul@NOSPAM.com)<43220><Xh+N/B+6CqUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: Starting with partial=3 full=20 attachments=0 verbose=1
Jan 30 16:43:47 saturne dovecot: imap(jul@NOSPAM.com)<43220><Xh+N/B+6CqUAAAAAAAAAAAAAAAAAAAAB>: Logged out in=664 out=76618 deleted=0 expunged=0 trashed=0 hdr_count=30 hdr_bytes=53690 body_count=0 body_bytes=0
Jan 30 16:43:47 saturne dovecot: imap(jul@NOSPAM.com)<43220><Xh+N/B+6CqUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: Deinit /var/vmail/nospam.com/julien/Maildir/xapian-indexes)
Jan 30 16:43:49 saturne dovecot: imap-login: Login: user=<jul@NOSPAM.com>, method=PLAIN, rip=::1, lip=::1, mpid=43223, TLS, session=<aMSq/B+6DKUAAAAAAAAAAAAAAAAAAAAB>
Jan 30 16:43:49 saturne dovecot: imap(jul@NOSPAM.com)<43223><aMSq/B+6DKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: Starting with partial=3 full=20 attachments=0 verbose=1
Jan 30 16:43:49 saturne dovecot: imap(jul@NOSPAM.com)<43223><aMSq/B+6DKUAAAAAAAAAAAAAAAAAAAAB>: Logged out in=521 out=13795 deleted=0 expunged=0 trashed=0 hdr_count=1 hdr_bytes=1985 body_count=1 body_bytes=10068
Jan 30 16:43:49 saturne dovecot: imap(jul@NOSPAM.com)<43223><aMSq/B+6DKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: Deinit /var/vmail/nospam.com/julien/Maildir/xapian-indexes)
Jan 30 16:43:59 saturne dovecot: imap-login: Login: user=<jul@NOSPAM.com>, method=PLAIN, rip=::1, lip=::1, mpid=43227, TLS, session=<PoY+/R+6EqUAAAAAAAAAAAAAAAAAAAAB>
Jan 30 16:43:59 saturne dovecot: imap(jul@NOSPAM.com)<43227><PoY+/R+6EqUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: Starting with partial=3 full=20 attachments=0 verbose=1
Jan 30 16:43:59 saturne dovecot: imap(jul@NOSPAM.com)<43227><PoY+/R+6EqUAAAAAAAAAAAAAAAAAAAAB>: Logged out in=89 out=1006 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
Jan 30 16:43:59 saturne dovecot: imap(jul@NOSPAM.com)<43227><PoY+/R+6EqUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: Deinit /var/vmail/nospam.com/julien/Maildir/xapian-indexes)
Jan 30 16:44:17 saturne dovecot: imap(jul@NOSPAM.com)<43218><z1Vz/B+657mZbXcp>: Logged out in=715 out=6760 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
Jan 30 16:44:17 saturne dovecot: imap(jul@NOSPAM.com)<43218><z1Vz/B+657mZbXcp>: FTS Xapian: Deinit /var/vmail/nospam.com/julien/Maildir/xapian-indexes)`

**Comment by jranma** [comment]
```
Jan 30 16:43:35 saturne dovecot: master: Warning: Killed with signal 15 (by pid=43179 uid=0 code=kill)
Jan 30 16:43:35 saturne dovecot: imap(jul@NOSPAM.com)<43096><N/jC7x+6D7OZbXcp>: Server shutting down. in=834 out=31424 deleted=0 expunged=0 trashed=0 hdr_count=2 hdr_bytes=10204 body_count=1 body_bytes=10068
Jan 30 16:43:35 saturne dovecot: imap(jul@NOSPAM.com)<43096><N/jC7x+6D7OZbXcp>: FTS Xapian: Deinit /var/vmail/nospam.com/julien/Maildir/xapian-indexes)
Jan 30 16:43:35 saturne dovecot: master: Dovecot v2.3.4.1 (f79e8e7e4) starting up for imap, lmtp, sieve, pop3 (core dumps disabled)
Jan 30 16:43:36 saturne dovecot: imap-login: Login: user=<jul@NOSPAM.com>, method=PLAIN, rip=153.109.119.41, lip=91.134.140.163, mpid=43210, TLS, session=<wKfh+x+6tLmZbXcp>
Jan 30 16:43:36 saturne dovecot: imap(jul@NOSPAM.com)<43210><wKfh+x+6tLmZbXcp>: FTS Xapian: Starting with partial=3 full=20 attachments=0 verbose=1
Jan 30 16:43:36 saturne dovecot: imap(jul@NOSPAM.com)<43210><wKfh+x+6tLmZbXcp>: Logged out in=52 out=596 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
Jan 30 16:43:36 saturne dovecot: imap(jul@NOSPAM.com)<43210><wKfh+x+6tLmZbXcp>: FTS Xapian: Deinit /var/vmail/nospam.com/julien/Maildir/xapian-indexes)
Jan 30 16:43:37 saturne dovecot: imap-login: Login: user=<jul@NOSPAM.com>, method=PLAIN, rip=::1, lip=::1, mpid=43212, TLS, session=<ALbu+x+6+KQAAAAAAAAAAAAAAAAAAAAB>
Jan 30 16:43:37 saturne dovecot: imap(jul@NOSPAM.com)<43212><ALbu+x+6+KQAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: Starting with partial=3 full=20 attachments=0 verbose=1
Jan 30 16:43:37 saturne dovecot: imap(jul@NOSPAM.com)<43212><ALbu+x+6+KQAAAAAAAAAAAAAAAAAAAAB>: Logged out in=149 out=1118 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
Jan 30 16:43:37 saturne dovecot: imap(jul@NOSPAM.com)<43212><ALbu+x+6+KQAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: Deinit /var/vmail/nospam.com/julien/Maildir/xapian-indexes)
Jan 30 16:43:44 saturne dovecot: imap-login: Login: user=<jul@NOSPAM.com>, method=PLAIN, rip=::1, lip=::1, mpid=43215, TLS, session=<CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43215><CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: Starting with partial=3 full=20 attachments=0 verbose=1
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43215><CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: fts_backend_xapian_get_last_uid
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43215><CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: Get last UID of INBOX (2aa527066a110c6083c20000f2488b2e) = 346
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43215><CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: fts_backend_xapian_refresh
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43215><CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: fts_backend_xapian_release (refresh)
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43215><CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: Committed 'refresh' in 1 ms
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43215><CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: fts_backend_xapian_get_last_uid
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43215><CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: Get last UID of INBOX (2aa527066a110c6083c20000f2488b2e) = 346
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43215><CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: fts_backend_xapian_lookup
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43215><CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: Query= body:"paroisse"
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43215><CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: 0 results in 1 ms
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43215><CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>: Logged out in=153 out=1513 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43215><CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: Deinit /var/vmail/nospam.com/julien/Maildir/xapian-indexes)
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43215><CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: fts_backend_xapian_release (unset_box)
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43215><CUth/B+6CKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: Committed 'unset_box' in 1 ms
Jan 30 16:43:44 saturne dovecot: imap-login: Login: user=<jul@NOSPAM.com>, method=PLAIN, rip=153.109.119.41, lip=91.134.140.163, mpid=43216, TLS, session=<OlFi/B+647mZbXcp>
Jan 30 16:43:44 saturne dovecot: imap(jul@NOSPAM.com)<43216><OlFi/B+647mZbXcp>: FTS Xapian: Starting with partial=3 full=20 attachments=0 verbose=1
Jan 30 16:43:45 saturne dovecot: imap-login: Login: user=<jul@NOSPAM.com>, method=PLAIN, rip=153.109.119.41, lip=91.134.140.163, mpid=43218, TLS, session=<z1Vz/B+657mZbXcp>
Jan 30 16:43:45 saturne dovecot: imap(jul@NOSPAM.com)<43218><z1Vz/B+657mZbXcp>: FTS Xapian: Starting with partial=3 full=20 attachments=0 verbose=1
Jan 30 16:43:47 saturne dovecot: imap-login: Login: user=<jul@NOSPAM.com>, method=PLAIN, rip=::1, lip=::1, mpid=43220, TLS, session=<Xh+N/B+6CqUAAAAAAAAAAAAAAAAAAAAB>
Jan 30 16:43:47 saturne dovecot: imap(jul@NOSPAM.com)<43220><Xh+N/B+6CqUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: Starting with partial=3 full=20 attachments=0 verbose=1
Jan 30 16:43:47 saturne dovecot: imap(jul@NOSPAM.com)<43220><Xh+N/B+6CqUAAAAAAAAAAAAAAAAAAAAB>: Logged out in=664 out=76618 deleted=0 expunged=0 trashed=0 hdr_count=30 hdr_bytes=53690 body_count=0 body_bytes=0
Jan 30 16:43:47 saturne dovecot: imap(jul@NOSPAM.com)<43220><Xh+N/B+6CqUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: Deinit /var/vmail/nospam.com/julien/Maildir/xapian-indexes)
Jan 30 16:43:49 saturne dovecot: imap-login: Login: user=<jul@NOSPAM.com>, method=PLAIN, rip=::1, lip=::1, mpid=43223, TLS, session=<aMSq/B+6DKUAAAAAAAAAAAAAAAAAAAAB>
Jan 30 16:43:49 saturne dovecot: imap(jul@NOSPAM.com)<43223><aMSq/B+6DKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: Starting with partial=3 full=20 attachments=0 verbose=1
Jan 30 16:43:49 saturne dovecot: imap(jul@NOSPAM.com)<43223><aMSq/B+6DKUAAAAAAAAAAAAAAAAAAAAB>: Logged out in=521 out=13795 deleted=0 expunged=0 trashed=0 hdr_count=1 hdr_bytes=1985 body_count=1 body_bytes=10068
Jan 30 16:43:49 saturne dovecot: imap(jul@NOSPAM.com)<43223><aMSq/B+6DKUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: Deinit /var/vmail/nospam.com/julien/Maildir/xapian-indexes)
Jan 30 16:43:59 saturne dovecot: imap-login: Login: user=<jul@NOSPAM.com>, method=PLAIN, rip=::1, lip=::1, mpid=43227, TLS, session=<PoY+/R+6EqUAAAAAAAAAAAAAAAAAAAAB>
Jan 30 16:43:59 saturne dovecot: imap(jul@NOSPAM.com)<43227><PoY+/R+6EqUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: Starting with partial=3 full=20 attachments=0 verbose=1
Jan 30 16:43:59 saturne dovecot: imap(jul@NOSPAM.com)<43227><PoY+/R+6EqUAAAAAAAAAAAAAAAAAAAAB>: Logged out in=89 out=1006 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
Jan 30 16:43:59 saturne dovecot: imap(jul@NOSPAM.com)<43227><PoY+/R+6EqUAAAAAAAAAAAAAAAAAAAAB>: FTS Xapian: Deinit /var/vmail/nospam.com/julien/Maildir/xapian-indexes)
Jan 30 16:44:17 saturne dovecot: imap(jul@NOSPAM.com)<43218><z1Vz/B+657mZbXcp>: Logged out in=715 out=6760 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0
Jan 30 16:44:17 saturne dovecot: imap(jul@NOSPAM.com)<43218><z1Vz/B+657mZbXcp>: FTS Xapian: Deinit /var/vmail/nospam.com/julien/Maildir/xapian-indexes)
```

**Comment by jranma** [comment]
search word was : 
`FTS Xapian: Query= body:"paroisse"`

**Comment by grosjo** [comment]
Are you sure there are email with "paroisse" in the INBOX or are they in subfolders ? Because the dovecot search is one folder at a time only

**Comment by jranma** [comment]
yes, the mail are located in the main INBOX. 
I have 3 mails which contains this word. If I type some keywords from the mail's SUBJECT, it's working ...

**Comment by grosjo** [comment]
Can you try a rescan of the said account ?
https://wiki2.dovecot.org/Tools/Doveadm/FTS
doveadm fts rescan -u you_user

There was a bug in body search some time ago, so maybe you updated recently ?

**Comment by jranma** [comment]
> Can you try a rescan of the said account ?
> https://wiki2.dovecot.org/Tools/Doveadm/FTS
> doveadm fts rescan -u you_user
> 
> There was a bug in body search some time ago, so maybe you updated recently ?

This command doesnt resolve problem.

But I notice something strange. 
A search on text:paroisse doesn't yield anything. On the other hand, text:paroiss or text:parois give me the expected result. "paroisse" is a single word, not part of an other word.

Problem is not on the IMAP client side, same results on different clients.

**Comment by slavkoja** [comment]
BTW @grosjo , the ``doveadm fts rescan ...`` deletes everything in user's ``xapian-indexes`` dir. I see mentioned this in doveadm doc, but is this expected with ``fts-xapian`` too (when you recommends it)?

**Comment by slavkoja** [comment]
> A search on text:paroisse doesn't yield anything. On the other hand, text:paroiss or text:parois give me the expected result. "paroisse" is a single word, not part of an other word.

I meet this in other project, where i use xapian. In my case it was caused by unsupported language (missing stemming for it) and thus only exact word matches was found. It happens too, if language support is disabled, by setting lang to none.

I partially solved it, by allowing wildcards matches, but it has own limitations.

**Comment by grosjo** [comment]
> BTW @grosjo , the ``doveadm fts rescan ...`` deletes everything in user's ``xapian-indexes`` dir. I see mentioned this in doveadm doc, but is this expected with ``fts-xapian`` too (when you recommends it)?

Well, the dovecot fts API does not allow to to a proper rescan , so all backends (fts-xapian included) have no choice but just delete existing indexes to it gets rebuild from scratch

**Comment by grosjo** [comment]
> > A search on text:paroisse doesn't yield anything. On the other hand, text:paroiss or text:parois give me the expected result. "paroisse" is a single word, not part of an other word.
> 
> I meet this in other project, where i use xapian. In my case it was caused by unsupported language (missing stemming for it) and thus only exact word matches was found. It happens too, if language support is disabled, by setting lang to none.
> 
> I partially solved it, by allowing wildcards matches, but it has own limitations.

Well, "paroisse" is a french word, I am having also plenty of french language emails (as a french speaker) and never experienced a probleme

Now, in fts-xapian, I overcome the issue you mentiond by indexing actual words directly instead of relying entirely on the stemming.

The fact that "parois" works , but not "paroisse" seems saying that there is a bug on the indexing part

**Comment by jranma** [comment]
> > A search on text:paroisse doesn't yield anything. On the other hand, text:paroiss or text:parois give me the expected result. "paroisse" is a single word, not part of an other word.
> 
> I meet this in other project, where i use xapian. In my case it was caused by unsupported language (missing stemming for it) and thus only exact word matches was found. It happens too, if language support is disabled, by setting lang to none.
> 
> I partially solved it, by allowing wildcards matches, but it has own limitations.

I've never set up any language options in dovecot, but if you have any settings for me, I'm happy to try.

**Comment by slavkoja** [comment]
this https://doc.dovecot.org/configuration_manual/fts/tokenization/ ?

**Comment by jranma** [comment]
`fts_languages = fr en`
did not help

Not sure which fts_tokenizers I should try

**Comment by slavkoja** [comment]
I really do not know how/if this works with fts-xapian.

**Comment by grosjo** [comment]
@jranma On my side, if I search "paroisse" in the body, I do find your email from github about the issue
so there is something very weird happening

Any other clue ?

**Comment by grosjo** [comment]
Can you try to do a "rescan" with the latest git, and search again for "paroisse" ?

**Comment by jranma** [comment]
OK, I will compile the latest git and try again. 

During the first install, I had to use
```
aclocal
autoconf
```
commands. Those are not included on your install procedure (I use debian). It's probably not the source of the problem, but I mention them. 

Can you please tell me difference between "doveadm fts rescan -u user" and "doveadm index -A -q \*" ? The second command rescann all the mailboxes on the system, but are there other differences ?

**Comment by jranma** [comment]
@grosjo Congratulations ! Latest git solved the problem

**Comment by grosjo** [comment]
Great. I will do an immediate minor release for this crucial bug

**Comment by grosjo** [comment]
@jranma : For your question : 
fts rescan actually delete all indexe to rebuilt from scartch
index -A : It removes all expunged emails from the index
