### ISSUE TITLE
Share index with notmuchmail?

### ISSUE THREAD

**Issue by tilllt** [grosjo/fts-xapian#69]
I am successfully running notmuchmail (https://notmuchmail.org/) on my Maildirs for years, a xapian based mail indexer. While i love it, sometimes, especially when i am elsewhere and cant fiddle with a Terminal, it would come handy to just be able to properly search my mails using a webmail client. Thats where fts-xapian would come into play. Obviously my use case is probably very specific, but i wondered if there could be a way for fts-xapian and notmuchmail to use a shared index, so i dont need to run TWO indexers for basically the same thing...

**Comment by tilllt** [comment]
https://github.com/jwm/dovecot-notmuch

there seem to have been done some work, but looks abandoned now.

**Comment by grosjo** [comment]
fts-xapian is a plugin for dovecot, and dovecot is compatible with Maildir format, and dovecot has a command-line to access the mails ("doveadm")

So you may have already a solution for your challenge: You may check
https://wiki.dovecot.org/Tools/Doveadm/Search
https://wiki2.dovecot.org/Tools/Doveadm/SearchQuery

**Comment by tilllt** [comment]
That's a nice suggestion, but notmuchmail is around for much longer afaik than the fts-xapian plugin and therefore has an extensive ecosystem of backends, frontends, scripts etc. https://notmuchmail.org/frontends/

Personally, i.e. i use the notmuchmail VIM integration, which is extremely clean and simple,

**Comment by grosjo** [comment]
@tilllt Can't do much about this. this pluging is used by dovecot, so if notmuchmail does not use dovecot, I can not do much about.
If you feel this is wrong, just re-open the issue

**Comment by tilllt** [comment]
There is a pool of eMails, that is indexed, using the SAME indexing tool, Xapian.

- Tool A (notmuch) chose index A as a format

- Tool B (fts-xapian) chose index B as a format, roughly 10 years later.

Dovecot does not dictate the format of the Index in my understanding, it queries Tool B for Data, Tool B accesses Index B and returns data to Dovecot. It is very probably that Tool B could be made interoperable with Index A. So _notmuch_ and the _fts-xapian plugin_ would use the same index. 

Even one step more is thinkable: since they are indexing the same type of data (EMails), it is extremely probable that Tool B could adapt its index to the format of Tool A. Since it has been released much later and arguably has the smaller user base, it would make sense if Tool B could try to adapt Index A - not the other way around.

If fts-xapian and notmuch would use the same kind of index (database) in the backend, users could take advantage of the functionality of both tools without wasting CPU / Diskspace on basically creating two indices of the same dataset which happen to be incompatible to each other, for not obvious reasons.

**Comment by grosjo** [comment]
Do you have a set of "terms" (as per Xapian api) used by notmuch ?
Also, is the email ID the same between dovecot and notmuch tools for each folder ?

**Comment by grosjo** [comment]
@tilllt No answer, so I close this for now. You may re-open it if you fill like answering my questions
