### ISSUE TITLE
Source code improvements

### ISSUE THREAD

**Issue by arodier** [grosjo/fts-xapian#76]
**Inconsistent style and indentation in the source code**
Some if not all of the source files are using a mix of tabulation and spaces, with sometimes a totally inconsistent indentation.

**Lack of comments in the source code**
I know the program still works, but it makes participating more difficult for new joiners. 

**Using a common style**
I propose to use a common style in the C++ files, for instance the google C++ styles, just because I have it included in emacs.

**Continuous integration**
Can we use one of the service on github to check the source code on every commit, like the style, the possible errors, etc

**Comment by arodier** [comment]
I am starting with the easiest, i.e. the style, but then, I will propose CI

**Comment by grosjo** [comment]
Hi
Happy to re-organise the includes
However, formatting fits very well VIM and putting at the end of function names make the code totally unreadable

**Comment by arodier** [comment]
Fair enough. What about the indentation composed of mixed tabs and spaces?

**Comment by arodier** [comment]
I don't really care about which style should be used in the source, as long as it is consistent in the whole repository. The _astyle_ seemed to do the job to me by reformatting everything at once.

Do we have another tool we can use to do the same job?

Thanks.

**Comment by grosjo** [comment]
I used unexpand & vim . Looks better ?

**Comment by arodier** [comment]
Yes, I think we are going in the right direction. I can still see some inconsistencies, but far less than before. Thanks!

**Comment by arodier** [comment]
I think it should be easy to add a badge about the current build status on travis-ci. It is free and a nice to have feature.
