### ISSUE TITLE
CJK support?

### ISSUE THREAD

**Issue by iredmail** [grosjo/fts-xapian#85]
Dear @grosjo 

- With latest 1.4.9b2, it can not index CJK (Chinese, Japanese, Korean) words, is it possible to implement this?
- Is the `XAPIAN_CJK_NGRAM` environment variable used in fts-xapian?

I tried to search a Chinese word in Roundcube webmail, with `verbose=1` in dovecot config file, i can see what it querying in Dovecot log file. for example:

```
... FTS Xapian: QUery 'subject:"test" OR from:"test" OR to:"test" OR cc:"test" OR bcc:"test" OR body:"test"' -> 1013 results
```

But with a Chinese word, e.g. `标题`, the `QUery` value is empty. If i prepend a wildcard mark, `*标题`, it correctly gets the query string, but nothing matched, although i'm sure there's at least one testing message should be matched.

```
... FTS Xapian: QUery 'subject:"*标题" OR from:"*标题" OR to:"*标题" OR cc:"*标题" OR bcc:"*标题" OR body:"*标题"' -> 0 results
```

**Comment by grosjo** [comment]
@iredmail 
Is it solved ?

**Comment by iredmail** [comment]
No issue at all, just requires at least 3 (Chinese) characters. I wonder is it possible to reduce it to 2?

**Comment by grosjo** [comment]
Try putting "partial=2" instead of "partial=3" in the dovecot.conf file

**Comment by iredmail** [comment]
Thanks. :)
