### ISSUE TITLE
Any plan for offering deb packages with PPA repo?

### ISSUE THREAD

**Issue by iredmail** [grosjo/fts-xapian#87]
Dear @grosjo 

Do you have any plan to offer deb packages of latest fts-xapian for Debian 9/10 and Ubuntu 18.04/20.04?

BTW, Debian 10 backports repo has dovecot-fts-xapian, but i don't think Debian/Ubuntu will offer latest version when you release a new version: https://packages.debian.org/search?suite=buster-backports&arch=any&searchon=names&keywords=dovecot-fts-xapian

I successfully built RPM package for CentOS 8 with the src.rpm file in this repo. it works fine.

**Comment by grosjo** [comment]
Would love to, but I have no clue how to push the packaged to Debian repositories. If you have some hints, let me know

**Comment by slavkoja** [comment]
it is in debian repo already, see https://packages.debian.org/bullseye/dovecot-fts-xapian

**Comment by iredmail** [comment]
Can we backport it to Debian 9? Also Ubuntu 20.04?

by the way, the main purpose of a PPA is always keep the package up to date. The package in official Debian/Ubuntu repos won’t be up to date due to the packaging policy.

**Comment by iredmail** [comment]
Dear all,

Any update?
I'm more than happy to donate USD $200 (via PayPal) for such PPA, with Debian 10+, Ubuntu 18.04+ support. :)

**Comment by iredmail** [comment]
Dear all,

Any update?

**Comment by grosjo** [comment]
If it's already in debian, why doing a PPA ? Maybe just upgrade your system to recent release ?

**Comment by iredmail** [comment]
> If it's already in debian, why doing a PPA ? Maybe just upgrade your system to recent release ?

Debian/Ubuntu have their packaging policy, they don’t always offer the latest fts-xapian. So the purpose of PPA is offering the latest version. 

Also, there’s no deb package for Ubuntu 18.04 and 20.04, they’re the latest 2 LTS editions for production, that means Ubuntu users won’t get fts-xapian deb package forever — unless compiling from source package.

**Comment by slavkoja** [comment]
AFAIK, the fts-xapian si more or less tied with particular dovecot version, nobody will build it for you, or more precise for your dovecot version, especially not for random old version.

**Comment by iredmail** [comment]
> AFAIK, the fts-xapian si more or less tied with particular dovecot version

@slavkoja This is not true.

According to the `README.md` file of this fts-xapian repo, `Dovecot 2.2.x (or above)` is supported, so it's not `tied with particular dovecot version`.

With rpm/deb packages, it's easier for sysadmins to install fts-xapian and keep it up to date, it also helps make this project spreading wider.

**Comment by grosjo** [comment]
```
# apt install dovecot-fts-xapian
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  dovecot-fts-xapian
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 30,1 kB of archives.
After this operation, 98,3 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu hirsute/universe amd64 dovecot-fts-xapian amd64 1.4.7-1 [30,1 kB]
Fetched 30,1 kB in 0s (158 kB/s)              
Selecting previously unselected package dovecot-fts-xapian.
(Reading database ... 262487 files and directories currently installed.)
Preparing to unpack .../dovecot-fts-xapian_1.4.7-1_amd64.deb ...
Unpacking dovecot-fts-xapian (1.4.7-1) ...
Setting up dovecot-fts-xapian (1.4.7-1) ...
```

THis shows that the plugins is already in Ubuntu (21 and above)
It is not the latest version and I will notice the maintainer

**Comment by iredmail** [comment]
Ubuntu 21 is not a LTS edition, hence not many people use it on production server. 18.04 and 20.04 are mostly used instead.

**Comment by grosjo** [comment]
There is a backport: https://packages.debian.org/buster-backports/dovecot-fts-xapian
not ok ?

**Comment by iredmail** [comment]
- Debian 10 has it in backports repo, so it's fine so far, but you will see the package out of date soon. And Debian 9 is deprecated, so no need to support Debian 9.
- Ubuntu 18.04 and 20.04 are the LTS (Long Term Support) editions, they're widely used as production server and will continue for a long time, that means people have to compile dovecot-fts-xapian manually, it's not the best way to install package, needless to say you need to re-compile again if you released a new version.

My suggestion is, we build a PPA repo for them so that all Debian/Ubuntu users are able to use the latest fts-xapian:

- Debian 10
- Ubuntu 18.04
- Ubuntu 20.04

**Comment by grosjo** [comment]
@iredmail Do you have any clue how to create a deb package, knowing that content is basically:
https://packages.debian.org/buster-backports/armel/dovecot-fts-xapian/filelist

**Comment by grosjo** [comment]
Can you try 
 ppa:grosjo/dovecot-fts-xapian

**Comment by jnahmias** [comment]
Hello @iredmail,
I maintain fts-xapian for Debian. It generally flows from there to Ubuntu. Perhaps requesting a backport on the Ubuntu side would achieve your goal. More info at: https://wiki.ubuntu.com/UbuntuBackports

**Comment by iredmail** [comment]
> Can you try
> ppa:grosjo/dovecot-fts-xapian

Dear @grosjo,

Failed on both Ubuntu 18.04 and 20.04:

```
E: The repository 'http://ppa.launchpad.net/grosjo/dovecot-fts-xapian/ubuntu focal Release' does not have a Release file.
```

**Comment by iredmail** [comment]
> Hello @iredmail,
> I maintain fts-xapian for Debian. It generally flows from there to Ubuntu. Perhaps requesting a backport on the Ubuntu side would achieve your goal. More info at: https://wiki.ubuntu.com/UbuntuBackports

Dear @jnahmias,

Thank you very much for maintaining a package in Debian/Ubuntu. :)

**Comment by grosjo** [comment]
@jnahmias  Can you make sure the official debian package is upgraded to 1.4.11 ? (1.4.7 is very old and many fixes were added)

**Comment by iredmail** [comment]
Maybe a stupid question: is it allowed by Debian/Ubuntu packaging policy to always roll out the latest release when it's announced by upstream? Or have to stick to one version and just apply patches to this version?

**Comment by jnahmias** [comment]
Debian is currently in the final stage of release for Debian 11 (bullseye), so very few changes are accepted right now. 
I have updated the package to 1.4.9a + patch for issue #90. Once it is accepted, I will be able to backport to Debian 10.
After the release is official, I can then upload newer versions and backport to prior releases.
FYI - a good link for following the package in Debian is: https://tracker.debian.org/pkg/dovecot-fts-xapian. You can subscribe to that page and receive updates via email.
Also, if you are interested, my packaging git repo is publicly available at: https://salsa.debian.org/debian/dovecot-fts-xapian
Hope this helps,
--Joe

**Comment by jnahmias** [comment]
@iredmail - to specifically answer your question, the unstable release can track upstream with very little lag, but the stable release has a different policy. See the suite update policy at the bottom https://release.debian.org/ for some more details.

**Comment by iredmail** [comment]
> @jnahmias Can you make sure the official debian package is upgraded to 1.4.11 ? (1.4.7 is very old and many fixes were added)

That's why a PPA is useful to fts-xapian users. :)

**Comment by grosjo** [comment]
https://tracker.debian.org/pkg/dovecot-fts-xapian

**Comment by iredmail** [comment]
It's out of date, `1.4.9a`.
A PPA is the best for fts-xapian and benefits all Debian/Ubuntu users. :)

**Comment by grosjo** [comment]
@iredmail maybe, but can you do it ?

**Comment by iredmail** [comment]
I'm not good at building deb packages, but rpm is ok. Sorry. 

But as mentioned in early reply, I'm willing to donate some $ for such PPA repo to benefit all Debian/Ubuntu users.

**Comment by grosjo** [comment]
I'll try to this up this week-end

**Comment by slavkoja** [comment]
@grosjo  you can get inspiration from my packages https://debs.slavino.org/pool/main/d/dovecot-fts-xapian/

**Comment by grosjo** [comment]
oh, you made it already ?
THis is a "PPA" repo already ?

**Comment by slavkoja** [comment]
i maintain my deb packages for long time (while i start to use it in production only in recent time), i check the history now and it is from 1.2.7 version, and all what i tell in this thread is based on my experiences with own package

**Comment by grosjo** [comment]
@iredmail  does this answer your request ?

**Comment by iredmail** [comment]
> @iredmail does this answer your request ?

No. The key point is "trust" (and up-to-date), only vendor's official apt/yum repositories are trusted by users.

**Comment by grosjo** [comment]
@slavkoja Can you share the scripts you are using to generate the DEB files ?
Thank you so much

**Comment by slavkoja** [comment]
@grosjo I am sorry, i do not understand what you want. All package files are in mentioned link in source package and to build package from them you have to use standard debian tool for it -- the ``debuild``

**Comment by grosjo** [comment]
I have little to no knowledge of Debian (Archlinux user here)

I installed a VM with Ubuntu. But before going through all the long doc, maybe you can just tell me how do you produce the DEB files from the git checkout (list of commands and/or files) ?

Thank you

**Comment by slavkoja** [comment]
> I have little to no knowledge of Debian (Archlinux user here)

I understand.

> I installed a VM with Ubuntu. But before going through all the long doc, maybe you can just tell me how do you produce the DEB files from the git checkout (list of commands and/or files) ?

I do not build packages from git, i use (mostly) always released sources for it. When i really need something not released yet, i still can patch it.

The simplest way to build package is to update the existing one:

1. download source package somewhere, eg. with ``dget`` or ``apt-get source``
2. update its source, if package properly set it, you can simple run ``uscan``
3. inspect source changes and change package if needed (this the simplest for you)
3. update the changelog entry with ``dch``
4. build package with ``debuild``

Then you have to decide for which debian release(s) and port(s) you want to publish it and then you will need to publish APT repository somewhere, if it have to be useful. And then you will need to monitor changes in used libraries and decide, if package requires rebuild...

----

Do  not get me bad please, but i will suggest you to leave this task for someone other, when you have no plans to utilize it. Create package is simple, create good package is not as simple and requires some experiences (as anything). And one simple cannot be expert on all packaging systems over the Linux world (i have experiences with debian and gentoo). It will be newer-end task and instead solving (potential) problems with your software, you will solve problems with packaging... As i mentioned already, when dovecot (or any linked library) version changes something in API/ABI, the binary package have to be rebuild...

Some days ago we talk with cmouse on dovecot IRC about experiences with 3th party repos badness (BTW, cmouse won with some package, which wipes whole system on uninstall). I believe, that you do not want be author of the new winner :-P

Once again, there are official packages for debian, if they have to be updated anyone can fill bug report against in debian bug tracking system (which is mostly useless as debian tracks new releases for maintainer). When someone is not satisfied with official package, still can mantain own one. But asking to do it from others (especially software author) for me is, ehm, strange...

**Comment by iredmail** [comment]
Sad no PPA from vendor yet.

Latest version is now 1.4.13, but:

- Debian 11 still ships 1.4.9a: https://packages.debian.org/bullseye/dovecot-fts-xapian
- Ubuntu 21.04 ships 1.4.7: https://packages.ubuntu.com/hirsute/dovecot-fts-xapian (Ubuntu 20.04 doesn't have this package).

It's impossible for Linux distribution vendors to roll out latest fts-xapian package. That's why we need a PPA for this -- a PPA from trusted party.

**Comment by jnahmias** [comment]
@iredmail - I am working on updating fts-xapian in Debian. Just started a new job, so probably have something in a week or two.

**Comment by grosjo** [comment]
https://tracker.debian.org/pkg/dovecot-fts-xapian

Deb being updated

**Comment by grosjo** [comment]
Debian is up to date
