### ISSUE TITLE
Immutable release files

### ISSUE THREAD

**Issue by jurajlutter** [grosjo/fts-xapian#91]
Hi,

I am curiour whethere it is possible to release immutable source archives for each release.

This will help us (as a package maintainers) to reliably fetch and verify released sources.

Thanks.

**Comment by grosjo** [comment]
Are you a package maintainer ?
What distribution are you dealing with ?

**Comment by jurajlutter** [comment]
I am a FreeBSD package (mail/dovecot-fts-xapian) maintainer.

**Comment by grosjo** [comment]
Can you clarify what is "immutable"  ?

**Comment by jurajlutter** [comment]
Immutable means properly rolled and released as .tar.gz, .tar.bz2, .tar.xz, alond with their known sizes and checksums.

Right now the files provided for download are github-generated archives that might change over the time, causing us (package maintainers) potential problems.

**Comment by grosjo** [comment]
Can you give an example of what do you expect to have ?

**Comment by jurajlutter** [comment]
Look at `https://github.com/hanslub42/rlwrap/releases/tag/v0.45.2` for example. Properly rolled source archive have size on their right side.

**Comment by grosjo** [comment]
@jurajlutter I really don't understand what do you call "the right side" ?

**Comment by jurajlutter** [comment]
<img width="997" alt="Screenshot 2021-07-03 at 16 41 21" src="https://user-images.githubusercontent.com/40118509/124357775-8f396e00-dc1d-11eb-8a1e-ad9a595fce61.png">

When you look at the right side of the picture, you will see the size (in kB). On the left side there are filenames. Those are properly rolled archives, released.

**Comment by grosjo** [comment]
Like this ? 
https://github.com/grosjo/fts-xapian/releases/tag/1.4.10a

**Comment by jurajlutter** [comment]
Yes, exactly. Thank you.
