### ISSUE TITLE
Verbose doveadm fts optimize output on stderr

### ISSUE THREAD

**Issue by slavkoja** [grosjo/fts-xapian#94]
Hi,

i recently decide to use your plugin in real and when i implement `doveadm fts optimize` in cron, i noticed that it has verbose output on stderr, eg.:
```
doveadm(user): Info: Expunging /path/to/xapian-indexes/db_6cb2f21c9b14e26035640000516f8e69
doveadm(user): Info: FTS Xapian: Expunging '/path/to/xapian-indexes/db_6cb2f21c9b14e26035640000516f8e69' done in 0.00 secs
...
```
It is a little problem, as i need to redirect its stderr to `/dev/null` to prevent zero informative daily emails, but it dangerous as i can loss error messages (if happen). I discuss this on dovecot's IRC, from where i was pointed, that it is plugin's implementation. To quote response:

    i think the author misuses i_info, he should be using e_debug
    or alternatively check set.mail_debug and use i_debug

I would expect, that these messages will be enabled only by asking debug/verbose output and to stderr will be going only real errors.

**Comment by grosjo** [comment]
Would latest git solve your issue ?

**Comment by slavkoja** [comment]
Thanks, I am sorry, i cannot test with git version now.

Be free to close it now, i will ask to reopen, after new version will be released and the issue will be still here.

**Comment by mstilkerich** [comment]
Hello,

  it is not fully fixed. I'm still getting these messages mailed when the daily fts optimize cronjob is executed.

> doveadm(usr): Info: FTS Xapian: Expunging /path/to/xapian-indexes/db_xyz' done in 0.00 secs

**Comment by mstilkerich** [comment]
Thanks, with the latest master there is no output when running doveadm fts optimize.
